### ISSUE TITLE
Ignore errors when typing wrong expression

### ISSUE THREAD

**Issue by mazing** [josdejong/mathjs#544] opened 2016-01-19 07:30 UTC
There seems to be a very good error handling, but is it possible to only fire `math.eval(expr)` if the expression is valid?

I use it with user input, so if the user is not done writing the expression, he/she gets an error. I would just ignore the error messages for the user, so he/she just can't see the processed value if the expression is not valid.

I have looked through the documentation, but I cannot find anything about handling erroneous expressions

**Comment by josdejong** [comment] 2016-01-19 08:07
You can enclose evaluating an expression in a try/catch block and do whatever you like with errors: display them, ignore them, log them to the console.

You could for example [debounce](https://davidwalsh.name/javascript-debounce-function) evaluation of user input: only evaluate the input 1 sec after the user stopped typing. That will prevent most temporary errors while typing.

**Comment by FSMaxB** [comment] 2016-01-19 09:16
This seems like a duplicate of #416. @mazing if I understand it correctly, you want mathjs to parse incomplete inputs so that you can present your users a value in realtime, even if the input isn't completely valid.

**Closed** 2016-06-01 10:50 UTC
Labels: question

**Comment by hluedeke** [comment] 2017-05-13 18:11
+1
