### ISSUE TITLE
Is custom bundling working?

### ISSUE THREAD

**Issue by dwertheimer** [josdejong/mathjs#2683] opened 2022-08-18 18:57 UTC
Maybe I'm just doing something wrong, but I am following the documentation as closely as possible.

**Describe the bug**
I have installed the latest mathjs from npm (`npm i mathjs --save`)
Trying to follow the instructions at:
https://mathjs.org/docs/custom_bundling.html#numbers-only
which says:
```js
// use light-weight, numbers only implementations of functions
import { create, all } from 'mathjs/number'

const math = create(all)
console.log(add(2, 3)) // 5
```

mathjs/number does not appear to exist.

<img width="684" alt="CleanShot 2022-08-18 at 11 55 27@2x" src="https://user-images.githubusercontent.com/8949588/185472663-73007534-acee-4203-ad2c-69cbb928e7bd.png">

**To Reproduce**
See above
Node v16.10.0

Am I doing something wrong?

**Comment by gwhitney** [comment] 2022-08-19 04:35
First of all, there is a problem in that documentation: the `add` on line 5 of the example code should be `math.add`. I will fix the documentation, but that's not the difficulty you're having, since you're not loading the module. I can verify that if you create a dummy npm project from scratch with `npm init`, make the package.json look like the one at the bottom of this post, and do `npm install mathjs`, then the example code works fine in node with the change I mentioned. (You may want to try exactly this on your end to verify that it is working.)

So something else is up in your environment. I see the message is from your IDE. Have you tried putting your test code in its own .js file and then executing that file with the `node` command? (Just to make sure whether the issue is with node resolving the import at runtime, rather than with however the IDE is doing resolution?) Assuming it is the case that node can't resolve the import: I assume you do have `"type": "module"` in your package.json?  Have you tried the alternate `import {create, all} from 'mathjs/lib/esm/number.js` ?  If none of those things help, we'll have to get deeper into the investigation...

Working package.json:
```
{
  "name": "dummy",
  "type": "module",
  "version": "1.0.0",
  "description": "can be deleted",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [
    "dummy"
  ],
  "author": "me",
  "license": "ISC",
  "dependencies": {
    "mathjs": "^11.0.1"
  }
}
```

**Comment by josdejong** [comment] 2022-08-19 08:15
Thanks for explaining all the pointers Glen, that is a good overview of possible issues.

This issue maybe because the TypeScript definitions of `mathjs/number` are missing: #2506

**Comment by gwhitney** [comment] 2022-08-19 11:06
Oh right, my working on that somehow got derailed. Another thing that needs attending to. But if we're going to get to auto-generated .d.ts files sometime fairly soon it might not be worth the effort to make the number-only .d.ts by hand at the moment....

**Comment by josdejong** [comment] 2022-08-19 11:59
👍 

> But if we're going to get to auto-generated .d.ts files sometime fairly soon it might not be worth the effort to make the number-only .d.ts by hand at the moment....

That will not be soon, so I think it will be worth creating a number only .d.ts manually for the time being.

I'll close this issue now, we can discuss further in #2506

**Closed by josdejong** 2022-08-19 11:59 UTC

**Comment by gwhitney** [comment] 2022-09-09 20:07
OK, I agree this is likely a consequence of #2506, so should be fixed when that (still open) bug is...
