### ISSUE TITLE
Consider adding support for unit when using math.round()

### ISSUE THREAD

**Issue by mofosyne** [josdejong/mathjs#3086] opened 2023-10-27 07:33 UTC
First example works as expected

```
math.round(math.evaluate("2.223"), 2).toString()
"2.22"
```

Second example doesn't work as expected

```
math.round(math.evaluate("2.223kg"), 2).toString() 
Uncaught TypeError: Unexpected type of argument in function round (expected: number or Complex or BigNumber or Fraction or Array or Matrix or DenseMatrix or SparseMatrix or string or boolean, actual: Unit, index: 0)
```

My desired behavior would be

```
math.round(math.evaluate("2.223kg"), 2).toString()
"2.22kg"
```

Possible challenges, is you will need to account for people doing strange units like "kg2.223" or "2.223kg^2", so addressing this will require parsing to properly capture the units.

**Comment by josdejong** [comment] 2023-10-27 07:44
I think this is a duplicate of https://github.com/josdejong/mathjs/discussions/2761, let's continue the discussion there.

**Closed by josdejong** 2023-10-27 07:44 UTC

**Comment by mofosyne** [comment] 2023-10-27 08:05
Ah missed that as I was only searching issue tickets. Thanks
