### ISSUE TITLE
feature: fraction lack of toTex

### ISSUE THREAD

**Issue by alvachien** [josdejong/mathjs#1472] opened 2019-04-12 03:53 UTC
It seems that fraction doesn't support toTex.

**Comment by josdejong** [comment] 2019-04-13 15:10
Can you give an example of what you mean?

**Comment by alvachien** [comment] 2019-04-15 03:39
@josdejong Thanks for the reply.

For instance, you create a fraction as following (https://mathjs.org/docs/datatypes/fractions.html):
`let testnumber = math.fraction('0.(3)');`

Is it possible to export testnumber with Tex format (via method toTex) which supported by math.parse?
`const node = math.parse('sqrt(x/x+1)');
node.toTex()      // returns '\sqrt{ {\frac{x}{x} }+{1} }'
`
Like following:
`
let testnumber = math.fraction('0.(3)');
testnumber.toTex() // return '\1 \over 3'
`

**Comment by josdejong** [comment] 2019-04-23 18:58
The `Fraction` class has a method `toLatex()`. This is not created by mathjs but built-in with the fraction library used by mathjs: https://github.com/infusion/Fraction.js. Does that address your issue?

**Comment by gwhitney** [comment] 2023-10-06 04:08
mathjs supports toTex() only on expressions, not arbitrary mathematical values. I don't see that changing. Closing as "works as intended".

**Closed** 2023-10-06 04:09 UTC
Labels: Works as intended
