### ISSUE TITLE
mathjs.simplify(1/3) gives 0.33333333... on bignumber configuration

### ISSUE THREAD

**Issue by onzag** [josdejong/mathjs#857] opened 2017-05-19 10:24 UTC
If you run the following piece of code.

```javascript
let mathjs = require("mathjs");

console.log(mathjs.simplify(mathjs.parse("1/3")));

mathjs.config({
        number: 'BigNumber'
});

console.log(mathjs.simplify(mathjs.parse("1/3")));
```

For some reason the second gives 0.333.... but this is a fraction that doesn't give a Z value and as so it should not be simplified to a floating point value it would never even have the precision, not even for 0.75 because 4/3 is a simpler value, it should behave exactly the same way that it does without bignumber configuration on.

**Comment by josdejong** [comment] 2017-05-21 17:52
Thanks for reporting, keeping `1/3` may make more sense indeed.

**Comment by firepick1** [comment] 2017-05-23 01:59
Jos, this is surprisingly tricky. The root cause is simplifyConstant. foldOp. The _eval is dividing 1/3.
If we attempt to fix this by not dividing, then we break the simplification of constants into a rational expression. This was quite unexpected and I've tried to think of a quick fix but nothing comes to mind.
The fastSimplify code dos not simplify constant expressions into a fraction, so there is no issue if folks just use fastSimplify.

**Comment by josdejong** [comment] 2017-05-25 13:21
Would it be possible to make the `simplifyConstant` logic a bit smarter? Like try to resolve an operation such as division into a Fraction or number, and only do so when this will not result in losing precision. In case BigNumbers are configured, either a BigNumber should be returned or a Fraction. I think Fraction should have highest preference, followed by returning a number or BigNumber (depending on config).

**Comment by firepick1** [comment] 2017-05-25 15:46
That sounds like a good approach for someone with a bigger sword. I just have a pocketknife. :)

**Comment by josdejong** [comment] 2017-05-27 18:20
One step at a time :D

**Comment by josdejong** [comment] 2018-02-25 16:19
I think this has been resolved in mathjs v4. Feel free to reopen this issue if that's not the case.

**Closed by josdejong** 2018-02-25 16:19 UTC
