### ISSUE TITLE
Usage in browser

### ISSUE THREAD

**Issue by recifx** [josdejong/mathjs#1943] opened 2020-08-14 19:20 UTC
Thanks for making this library available.
I am loading the math.js file as suggested in the website:
`    <script src="js/math.js" type="text/javascript"></script>`
and in a script that is also loaded from my html file, I have:
`let a = math.zeros(3, 2)`
that seems to create a 3x2 matrix with zeros, but when I try:
` math.multiply(a, 5)`
I get an error:
```
math.js:12258 Uncaught Error: Cannot convert "[[0, 0], [0, 0], [0, 0]][[0, 0], [0, 0], [0, 0]]" to a number
    at convert (math.js:12258)
```
The datatype of the matrix `a` is `undefined`
Can you let me know how I should go about using `math.js` in the browser? Thanks.

**Comment by josdejong** [comment] 2020-08-15 08:07
Thanks for reporting. I'm not sure how to reproduce your issue. In the examples section there is a set of browser examples that may help getting started:

https://mathjs.org/examples/index.html
https://mathjs.org/docs/getting_started.html#browser

**Comment by m93a** [comment] 2021-07-01 02:09
Closing as "cannot reproduce". If it's still an issue, let us know :)

**Closed** 2021-07-01 02:09 UTC
Labels: question
