### ISSUE TITLE
got wrong result when calculate tan(90 deg)

### ISSUE THREAD

**Issue by phoenixor** [josdejong/mathjs#1589] opened 2019-08-09 15:36 UTC
when i use mathjs to calculate tan(90 deg) in my wxapp project, i got 16331239353195370 instead of an error. and i have no idea how to solve it.
By the way, when caculating 0.1+0.2, it does on give me 0.3

**Comment by ericman314** [comment] 2019-08-09 15:47
Unfortunately, this is a problem due to round-off error and there is no easy solution. Duplicate of #133.

**Closed by ericman314** 2019-08-09 15:47 UTC
