### ISSUE TITLE
Hide implicit multiplication (symbols) when using math.simplify to evaluate custom functions

### ISSUE THREAD

**Issue by samueltlg** [josdejong/mathjs#1137] opened 2018-06-16 10:12 UTC
Hi there,

I have this piece of code:
```javascript
function genRandomInt(min, max) {
  return min + Math.floor(Math.random() * (max - min + 1))
}

genRandomInt.transform = function(min, max) {
  const res = genRandomInt(min, max)
  return res
}

math.import({
  r: genRandomInt
})

const node = math.parse('r(1,4)x')

const rules = [
]

const simplified = math.simplify(node)
console.log(simplified.toTex({implicit: 'hide'}))
katex.render(simplified.toTex(), elem)
```

I am looking to use the simplify function in order to evaluate _custom functions only_ ; hence I am not using `math.eval`. However, it seems that using `math.simplify` seems to make multiplication explicit, hence the `{ implicit: 'hide' }` option belonging to `toTex` has no effect. Is there a way to retain this implicit multiplication when using simplify?

Also, I was looking for a way to perhaps use \times and \cdot in TeX output, does `toTex` cater for this? I cannot seem to find this anywhere.
Furthermore, after looking at the documentation for simplify, it does state that you can use rules, but I am unable to find a way to use it such that, for example, only custom functions are evaluated, is this also a possibility?

Many thanks,
Sam

**Comment by josdejong** [comment] 2018-06-24 16:30
Thanks for reporting!

A simpler example demonstrating the issue is:

```js
const f = math.parse('2x')
console.log(f.toString({implicit: 'hide'})) // '2 x'
const simplified = math.simplify(f)
console.log(simplified.toString({implicit: 'hide'})) // '2 * x' instead of '2 x'
```

The `simplify` function somewhere loses the `implicit` property of the original OperatorNode `*`, it would be nice if it can keep track on implicit multiplication when multiplications are left unchanged.

**Comment by josdejong** [comment] 2018-07-07 12:01
This should be fixed now in `v5.0.2`

**Comment by samueltlg** [comment] 2018-07-08 21:19
Great! Thanks

**Comment by josdejong** [comment] 2018-09-30 16:31
@Radivarig can you give an example of when this still happens? It works as expected for example in the following case:

```js
math.simplify('2 x').toString() // '2 x'
```

**Comment by Radivarig** [comment] 2018-09-30 21:05
@josdejong 
```bash
$ node -v
v9.10.1

$ cat package.json | grep mathjs
  "mathjs": "^5.1.2"
```
```js
// index.js
const math = require ("mathjs")

const expr = "2x + 3x"
const n0 = math.parse (expr) // does not work
const n1 = math.simplify(n0) // does not work
const n2 = math.parse ("5x") // works when no operators

;[n0, n1, n2].map (function(n, i) {
  const ni = `n${i}`
  console.log (ni, n.toString ())
  console.log (ni, n.toString ({ "implicit": "hide" }))
  console.log (ni, n.toString ({ "implicit": "show" }))
  
  console.log (ni, n.toTex ({ "implicit": "hide" }))
  console.log (ni, n.toTex ({ "implicit": "show" }))
  console.log ()
})
```
```bash
$ node index.js 
n0 2 x + 3 x
n0 2 x + 3 x
n0 2 * x + 3 * x
n0 2~ x+3~ x
n0 2\cdot x+3\cdot x

n1 5 * x
n1 5 * x
n1 5 * x
n1 5\cdot x
n1 5\cdot x

n2 5 x
n2 5 x
n2 5 * x
n2 5~ x
n2 5\cdot x
```

**Comment by Radivarig** [comment] 2018-09-30 21:13
@josdejong 
```bash
$ node -v
v9.10.1

$ cat package.json | grep mathjs
  "mathjs": "^5.1.2"
```
```js
// index.js
const math = require ("mathjs")

const expr = "2 x + 3 x"
const n0 = math.parse (expr) // works
const n1 = math.simplify(n0) // does not work

;[n0, n1].map (function(n, i) {
  const ni = `n${i}`
  console.log ("\n" + ni,n.toString ())
  console.log (ni, n.toString ({ "implicit": "hide" }))
  console.log (ni, n.toString ({ "implicit": "show" }))
  
  console.log (ni, n.toTex ({ "implicit": "hide" }))
  console.log (ni, n.toTex ({ "implicit": "show" }))
})
```
```bash
$ node index.js 

n0 2 x + 3 x
n0 2 x + 3 x
n0 2 * x + 3 * x
n0 2~ x+3~ x
n0 2\cdot x+3\cdot x

n1 5 * x
n1 5 * x
n1 5 * x
n1 5\cdot x
n1 5\cdot x
```

**Comment by josdejong** [comment] 2018-10-03 13:45
Ah ok. 

Right now implicit multiplication is only retained in parts of the expression that are not changed when simplified, like `2 x`. When replacing parts of the expression, output is always explicit multiplication. 

I guess we could improve `simplify` to check cases like `2x + 3x` where both sides of the expression have an implicit multiplication and if so keep the implicit multiplication in place. 

Anyone interested in picking this up?

**Comment by josdejong** [comment] 2022-09-02 15:08
This has been fixed in the meantime, closing this issue now.

**Closed by josdejong** 2022-09-02 15:08 UTC
Labels: feature, help wanted

**Comment by nickkolok** [comment] 2024-02-28 21:19
```
$ cat package.json | grep mathjs
    "mathjs": "^11.5.1"
```

`math.simplify(math.parse('-5x-(-2)')).toTex()` -> `2-5\cdot x`

As a workaround: is there a way to replace explicit multiplication with implicit whenever possible?

**Comment by nickkolok** [comment] 2024-02-28 23:27
P.S. Looks like `el = math.simplify(el, [{l:'n1*n2', r: 'n1 n2'}]);` does the job. However, this is still strange.

**Comment by josdejong** [comment] 2024-02-29 07:34
> As a workaround: is there a way to replace explicit multiplication with implicit whenever possible?

Yes, you can parse the expression, then transform it by changing all OperatorNode's that are a multiplication (`node.op === '*'`), set the value of property `node.implicit` to `true`.

Docs: https://mathjs.org/docs/expressions/expression_trees.html -> search for "transform"
