### ISSUE TITLE
.d.ts for mathjs/number

### ISSUE THREAD

**Issue by riceyeh** [josdejong/mathjs#2331] opened 2021-10-04 08:20 UTC
There is @types/mathjs for import from ‘mathjs’. However, when import from ‘mathjs/number’, @types/mathjs is not associated with in vscode IDE. How is this solved?

**Comment by m93a** [comment] 2021-10-04 14:25
Hey Rice,
this looks like a duplicate of #2284. Currently, we don't have type definitions for `mathjs/number` (and we're looking for a PR). Also, `@types/mathjs` should be deprecated, since `mathjs` ships its own types.

**Closed by m93a** 2021-10-04 14:25 UTC
