### ISSUE TITLE
Simplify giving wrong output I believe

### ISSUE THREAD

**Issue by aminemarref** [josdejong/mathjs#2015] opened 2020-10-30 16:43 UTC
Hello,

The following (ungodly) expression:
`((((((((((1)) + ((0)))) * ((x + 2))) + (((x + 1)) * ((((1)) + ((0))))))) * ((x + 3))) - ((((x + 1) * (x + 2))) * ((((1)) + ((0)))))) / (((x + 3)) ^ (2)))`

is simplified (using simplify) to:
`1 * x + 2 + x + 1 * 1 * x + 3 - (x + 1) * (x + 2) * 1 / (x + 3) ^ 2`

but it should be:
`(1 * x + 2 + x + 1 * 1) *( x + 3) - (x + 1) * (x + 2) * 1 / (x + 3) ^ 2`

Any thoughts?

Thanks.

**Comment by josdejong** [comment] 2020-10-31 13:29
I do not get the same output as you, all seem correct when I execute the following in the JavaScript console of the website https://mathjs.org: 

```js
const expr = math.parse('((((((((((1)) + ((0)))) * ((x + 2))) + (((x + 1)) * ((((1)) + ((0))))))) * ((x + 3))) - ((((x + 1) * (x + 2))) * ((((1)) + ((0)))))) / (((x + 3)) ^ (2)))')
console.log(expr.evaluate({ x: 10 })) // 0.9881656804733728
console.log(expr.evaluate({ x: 100 })) // 0.9998114808181733

const exprSimplified = math.simplify(expr)
console.log(exprSimplified.toString()) // '((2 * (x + 1) + 1) * (x + 3) - (x + 1) * (x + 2)) / (x + 3) ^ 2'
console.log(exprSimplified.evaluate({ x: 10 })) // 0.9881656804733728
console.log(exprSimplified.evaluate({ x: 100 })) // 0.9998114808181733
```

**Comment by gwhitney** [comment] 2023-10-03 06:39
Since the issue could not be confirmed and there was no followup, closing.

**Closed by gwhitney** 2023-10-03 06:39 UTC
Labels: Works as intended
