### ISSUE TITLE
Absolute value symbol in parser

### ISSUE THREAD

**Issue by ChristopherChudzicki** [josdejong/mathjs#1307] opened 2018-10-31 00:11 UTC
It would be great if the parser accepted expressions containing pipes for absolute values and vector/matrix norms:

```js
math.eval('|-5|+2') // 7
math.eval('|[3, 4]| + |[5, 12]'|) // 18 ... using L2 norm for vectors/matrices
``` 

Has this been considered in the past?

Potential issues:
  1. Traditional absolute value / norm notation uses the same character for opening groups and closing groups, so capturing groups correctly might be difficult. This doesn't seem insurmountable, though...just need to keep track of whether pipe count is even/odd.
  2. The parser currently uses pipes for `bitOr`, with syntax `math.eval('3|6')` yielding `math.bitOr(3, 6)`. I'm not sure if this causes any ambiguous expressions. The only slightly ambiguous expression I can think of is `math.eval('3|-8|2')`:
     - is this `bitOr(3, BitOr(-8, 2))` (current interpretation) 
     - is this `3*abs(-8)*2` (implicit multiplication)

If that really is the only ambiguous case, we could just stick with the current interpretation. But I'm not sure if I've thought of the only ambiguous case...

**Comment by josdejong** [comment] 2018-11-03 08:48
Thanks for your suggestion @ChristopherChudzicki . The pipe characters for norm are very common in mathematics, it looks very natural too me. We haven't considered this before.

1. I don't think this will be an issue, it's like a string `"text"` which also starts and ends with the same character
2. I indeed think there will be ambiguities. Your example `3|-8|2` is very clear, but also `3|-8|2|3` can mean different things. I don't see a solution for this unfortunately :(

**Comment by rmvermeulen** [comment] 2019-01-03 17:57
Maybe if you enforce some spacing or parens in that case? 
`3 * abs(-8) * 2` = `3 |-8| 2` or `3(|-8|)2`
`bitOr(3, BitOr(-8, 2))` = `3|-8|2` or `3 | -8 | 2`
`3*abs(bitOr(-8,2))` = `3(|-8|2|)`

**Comment by josdejong** [comment] 2019-01-03 19:47
When you need to use parentheses around pipe character we sort of lose the clear syntax. I think I would prefer to simply use an explicit `abs(...)` or `norm(...)` in these cases.

**Comment by gwhitney** [comment] 2023-10-06 04:38
Duplicate of #3044. Will close this, and reference it over there.

**Closed by gwhitney** 2023-10-06 04:38 UTC
