### ISSUE TITLE
Is possible to find Root of the functions

### ISSUE THREAD

**Issue by Aloento** [josdejong/mathjs#2574] opened 2022-05-24 12:03 UTC
for example find the possible x for "2x + x = 0"

**Comment by josdejong** [comment] 2022-05-27 11:53
That's not supported, though it would be awesome. I think this is a duplicate of #38. Are you thinking about a numerical solution or algebraic?

**Comment by Aloento** [comment] 2022-05-27 13:45
the numerical solution is easier to solve with code I think.
x = 0

**Comment by josdejong** [comment] 2022-05-31 09:15
The numerical solution is indeed the nicest. I doubt if it's the easiest though 😄 . Let's close this issue in favor of #38 and continue any discussion there.

**Closed by josdejong** 2022-05-31 09:15 UTC
Labels: question
