### ISSUE TITLE
Proposal: Expose `isMatrix`

### ISSUE THREAD

**Issue by ChristopherChudzicki** [josdejong/mathjs#2444] opened 2022-02-22 23:31 UTC
As a developer using mathjs to build applications, I'd like to be able to determine whether an object is a matrix in a type-safe way. To this end, a boolean-returning function `isMatrix` with Typescript signature `(value: unknown): value is Matrix` would be useful.

The immediate use-case for this function in my application is to compile MathJS expressions to functions that evaluate to arrays rather than DenseMatrix instances, since other libraries I use expect an array. So for example:
```ts
// isMatrix exists but is not documented or typed
import { MathNode, EvalFunction, isMatrix } from 'mathjs' 

const compile = (node: MathNode): EvalFunction => {
  const { evaluate: rawEvaluate } = node.compile()
  const evaluate = (scope: unknown) => {
    const result = rawEvaluate(scope)
    if (isMatrix(result)) {
      // result's type should be appropriately narrowed to Matrix
      return result.toArray()
    }
    return result
    return { evaluate } 
}
```

**Proposal:** Document and provide a type definition for `isMatrix` from `src/util/is` as an export of MathJS. _It is already exported, just not documented or typed._

The `isMatrix` function would provide useful type refinement. Usually this sort of refinement is possible with something like `thing instanceof SomeClass`, but since the Matrix/DenseMatrix classes are created dynamically, they can't be exported by MathJS, so the `instanceof` approach doesn't work great. _In contrast, the `instanceOf` does work very well for some things (like `node instanceof AssignmentNode`, for example)_.

_Probably not Not all the functions from src/util/is are work exporting; e.g., `isRegexp` and other refinement approaches, like `instanceof`, work fine_.

@gwhitney raised the question of whether a function like `isMatrix` should be useable within expressions... I personally am indifferent on that. Would that necessarily add significant overhead?

**Comment by ChristopherChudzicki** [comment] 2022-02-22 23:36
Related: https://github.com/josdejong/mathjs/pull/2432 adds typedefs for all of `src/util/is`, back when I thought they were purposefully exported by MathJS. (I guess a separate issue is... if these are not really publish functions, should they not be exported by the bundle?)

**Comment by gwhitney** [comment] 2022-02-23 03:22
This proposal looks fine to me. The main question I have is whether there are other candidates that we should promote at the same time, while we are at it? Thoughts?

mathjs appears to have a pretty strong tradition that any function "published" in the API should also work in expressions, and I don't see any reason why isMatrix is any exception; it can quite reasonably be called as a function in an expression and return a boolean. As far as overhead, the issue of one more function when there are hundreds already is not a major concern (we just need to make sure to avoid adding _too_ many functions willy-nilly, but one either way is immaterial).

Finally, we'll let @josdejong weigh in as to the "status" of functions that are actually being exported in the bundle but which are not documented in the API and not available for use in expressions, and whether or not we should for each one of the "isXXX" functions either fully publish it or make it only available internally, i.e. not be accessible in the exported bundle.

Thanks! (You probably want to hold off on a PR for this until we have some more feedback on the most desirable scope here.)

**Comment by josdejong** [comment] 2022-02-28 10:55
Makes sense to document `isMatrix` if it's missing. There is a whole list of `isSomething` functions, if there are more missing we should add them to the TypeScript definitions. Thanks for bringing this up @ChristopherChudzicki .

**Comment by gwhitney** [comment] 2022-02-28 15:07
Well the biggest "difference" about isMatrix isn't just that it's not documented -- it's not a full-fledged mathjs function. In particular it is not accepted in the parser. It's solely exposed in the math object as an (undocumented) JavaScript-only function.

I was assuming you don't really want two "tiers" of functions in mathjs, the full-fledged ones and some available only in JavaScript, primarily because of examples like `parse` which feel very "external" and yet are internally available in the parser as well.

The vast bulk of functions that are available in JavaScript but not in the parser are ones in "is.js". So I sort of assumed you'd want to curate ones that would become full fledged, and then stop exporting the ones that don't seem like they should be full-fledged.

Of course I could be wrong, and you want two tiers of functions. In that case, I think the "is"s that are exported should still be documented somewhere and their distinction that they are javascript-only made clear.

**Comment by josdejong** [comment] 2022-03-01 09:49
Oooh, good point Glen, I hadn't realized that.

> I was assuming you don't really want two "tiers" of functions in mathjs

Yes indeed, you're right. It is important to keep the library consistent in this regard, and only expose "fully fledged" functions. So we have to make some steps there 😅 .  It feels cumbersome but I think we should indeed create (typed) wrapper functions around the functions like  `isMatrix` and make these wrapper functions public.

**Comment by gwhitney** [comment] 2022-03-02 21:45
OK, excellent. It is great to have that clarity. So for each `is` function which is currently not documented/available in the parser, there needs to be a decision as to whether to make it "fully fledged" or to stop exporting it in the mathjs object. Clearly, for `isMatrix` the way to go is to make it full. The remaining functions in question are:
  'isNumber',
  'isComplex',
  'isBigNumber',
  'isFraction',
  'isUnit',
  'isString',
  'isArray',
  'isCollection',
  'isDenseMatrix',
  'isSparseMatrix',
  'isRange',
  'isIndex',
  'isBoolean',
  'isResultSet',
  'isHelp',
  'isFunction',
  'isDate',
  'isRegExp',
  'isObject',
  'isNull',
  'isUndefined',
  'isAccessorNode',
  'isArrayNode',
  'isAssignmentNode',
  'isBlockNode',
  'isConditionalNode',
  'isConstantNode',
  'isFunctionAssignmentNode',
  'isFunctionNode',
  'isIndexNode',
  'isNode',
  'isObjectNode',
  'isOperatorNode',
  'isParenthesisNode',
  'isRangeNode',
  'isSymbolNode',
  'isChain',

I would imagine to be parallel with isMatrix, both isDenseMatrix and isSparseMatrix should become full. Care to provide guidance on the others? Or principles by which the disposition can be decided? Thanks.

**Comment by ChristopherChudzicki** [comment] 2022-03-03 02:30
@gwhitney Thanks for the thought you've put into this issue, an apologies that I disappeared a little bit! Having thought about this and looked into it a little bit more, my perspective is:
- the functions in `src/util/is` should probably be regarded as implementation details of MathJS. These functions are generally dead-simple, untyped, boolean-returning functions. 
- MathJS already exports a few typed `isX` functions and they are all typed.  **so if more are exposed as top-level exports, they should also be typed as you have said.**

I originally focused on `isMatrix` because, unlike `isOperatorNode`, it cannot be mimicked with the Typescript-declared exports of MathJS. Export `isMatrix` and some others might still be useful and worthwhile, however I think a more fundamental issue is **MathJS should declare `Matrix`, `DenseMatrix`, `SparseMatrix` as constructor types** (which is already the case for the Node types). 

What I mean is this. Suppose you want a function `isOperatorNode`. Then in Typescript, this works perfectly well:
```ts
// this works well
import { OperatorNode } from 'mathjs' 

const isOperatorNode = (x: unknown): x is OperatorNode => x instanceof OperatorNode
```
In contrast, 
```ts
// this does NOT work
import { Matrix } from 'mathjs' 

const isMatrix = (x: unknown): x is OperatorNode => x instanceof Matrix
```

The reason that the first case works but the second does not is that the type definitions for MathJS declare both an OperatorNode interface (for instances of OperatorNode) *and* that declares OperatorNode as a top-level export **that is a constructor**. Here are the definitions, omitting a bunch of irrelevant stuff:
```ts
declare namespace math {
  interface Matrix { /** properties & methods */ }
  interface OperatorNode { /** properties & methods */ }
  interface OperatorNodeCtor { new (/**args */): OperatorNode; }

  interface MathJsStatic {
    OperatorNode: OperatorNodeCtor;
    // but no MatrixCtor analogue!
  }
}

// declares MathJsStatic as the exports of mathjs
declare const math: math.MathJsStatic;
export as namespace math;
export = math;
```

So I propose:
- Declare Matrix (and propably DenseMatrix?) as top-level exports of MathJS in the type definitions, similar to what is done for the Nodes. This would enable type-safe `instanceof` checks. 

It may additionally be useful to export some typed `isX` functions, but I actually think ☝️ is the fundamental issue, and would enable users Typescript users to implement dead-simple `isMatrix` functions of their own. (without adding some @ts-ignores).

**Comment by gwhitney** [comment] 2022-03-03 17:52
Thanks for the insight, Christopher, and I definitely have no objection to refining the Matrix and DenseMatrix and SparseMatrix class typings in mathjs if you would like to file a PR that does that. But it remains a fact that you have uncovered a large collection of functions, the "is" functions listed above, which are currently being exported but are not available in the parser and are not documented. So we do need to regularize each of them one way or the other, either by fleshing them out or by stopping their export, and Jos will need to decide which way to go on each one or give principles by which that decision is made.
In the particular case of these "is...Matrix" ones, if it seems as though folks are going to have to define typescript type predicates anyway, and given they're exported already, my intuition is why not just go ahead and supply properly typed and documented type predicates also available in the parser? That way clients won't have to roll their own, even if it is "dead simple."

**Comment by josdejong** [comment] 2022-03-04 09:07
Thanks guys, good discussion. Here my thoughts, I think we're on the same page:

1. It's valuable to export all `is*` functions ("so clients don't have to role their own"). All of these functions _are_ already exported, they are only missing in the TypeScript definitions
2. If possible it would be great to have the `is*` functions defined correctly as TypeScript type guards, that makes them much more usable
3. `Matrix`, `DenseMatrix`, and `SparseMatrix` are _also_ already exported but are probably missing in the TypeScript definitions
4. I'm still a bit in doubt about turning the `is*` functions into typed functions. It would be good for consistency. However, it will add hardly any value, and adds more code and complexity. Since these functions are already exposed for long time, this is not a regression, and turning them into typed functions will not be a breaking change but "only" improve error messaging. I think we can address this separately from this PR, and keep this PR focused on "just" bringing the TypeScript definitions on par with what is already there. 
5. Refactoring the library into TypeScript would be great 😁  but that's a separate topic.

**Comment by gwhitney** [comment] 2022-03-04 15:32
On (4), I don't have a view about whether the `is*` functions are `typed-function` but what troubles me is that they are exported without being documented or being available in the parser, which seem like fairly significant inconsistencies to me. I am not saying whether all of the documentation/making available in parser has to be done in one PR, but I would strongly recommend doing it and am happy to help with the work. If you want just typescript typings for the moment, there is PR #2432 which could be reviewed and merged. But either way, I'd strongly recommend keeping mathjs exports consistently documented and available in the parser, without too much delay.

One important question: does the implementation of a function have to be a typed-function for it to be made available in the parser? I don't actually see why that's strictly required. But maybe it's as strong a convention as the other aspects of a "fully fledged" mathjs function?

Finally on (5), are you contemplating (re)writing mathjs entirely in TypeScript? How would that affect using it from javascript? And isn't the whole typed-function thing sort of redundant then? (Anyhow that's clearly off topic here, so feel free not to respond or at least not in this thread.)

**Comment by josdejong** [comment] 2022-03-07 11:29
Totally agree, the `is*` functions that are there already should be documented and be added to the TypeSrcript definitions.  Thanks for your help on this. I suggest let's tackle this in small steps, and for now keep the functions as they are and just document them and create definitions.

> does the implementation of a function have to be a typed-function for it to be made available in the parser?

The parser just accepts any input, including any function. mathjs can do fully without typed-function, and it does so in the plain number implementation exported via `'mathjs/number'`. The reasons to define a function as typed-function is: better error messages, makes it easy to define multiple signatures, makes it possible to automatically convert arguments to allow mixing signatures (like solve `add(number, BigNumber)`), and allowing to extend a function with new signatures ([see example](https://mathjs.org/examples/advanced/custom_datatype.js.html)). So it's "good habit" and in line with the architecture to use typed-functions, but not breaking anything if a function is not a typed-function.

> Finally on (5), are you contemplating (re)writing mathjs entirely in TypeScript?

It is a vague wish. But will be a huge undertaking. Really huge. It probably requires first putting the architecture upside down to make it better aligned with what TypeScript can understand. Not sure though.

**Comment by ChristopherChudzicki** [comment] 2022-03-10 01:29
Agree that an incremental approach is good. 

@josdejong Generic question: As far as MathJS is concerned, are there any advantages to making a function typed (in the of [typed-function](https://github.com/josdejong/typed-function), not Typescript) if the function *never* throws?

I would suggest that the `isX` functions should in fact never throw.
- **`isX(a)`**: think it's very reasonable that `isX` should never throw when invoked with a single argument (everything either is an X or isn't, so always return `true/false`).
- **`isX(a, b,...)`**:  It might seem reasonable invoking with multiple args should throw, but that precludes some important use cases.

    For example, a common use-case for predicates filtering an array, and `someArray.filter(isX)` calls `isX` with three arguments: `(item, index, array)`. So it shouldn't throw with three arguments.  And if it doesn't throw with 1 arg or 3 args... probably it just should accept any number of arguments.

    _One could suggest that in the filtering example, `isX` should be called as `someArray.filter(item => isX(item))`. From a Typescript perspective, that's undesirable because the anonymized version won't have the same type predicate behavior. See https://github.com/microsoft/TypeScript/issues/20218#issuecomment-346343617_

**Comment by josdejong** [comment] 2022-03-10 09:12
Yes you're right, the added value of `typed-function` for the `isX` functions is really minimal: the `isX` function do accept `any` as first parameter. So it would only protect against accidentally calling the function with more than one argument. So, I think it's fine to be pragmatic here and keep the `isX` functions as-is right now: not a `typed-function`.

**Comment by ChristopherChudzicki** [comment] 2022-03-10 13:20
@josdejong
> So it would only protect against accidentally calling the function with more than one argument

I think there are good reasons that they should not throw even if called with multiple args, see previous comment for details.

Anyway, I've updated #2430 to reflect the discussion here.

**Comment by gwhitney** [comment] 2022-03-17 22:48
Proposal accepted, will be completed by items in #2487.

**Closed by gwhitney** 2022-03-17 22:48 UTC
