### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'evaluate')

### ISSUE THREAD

**Issue by feraskh0378** [josdejong/mathjs#2596] opened 2022-06-13 05:21 UTC
Hi,

I am using mathjs with electron - react app.
I got the error in the Title when calling "evaluate", can you please help? what is the issue?

I am doing the following:

import { evaluate } from 'mathjs'

evaluate(arg[1],scope)

my arg and scope:

![image](https://user-images.githubusercontent.com/107384833/173284965-a65b5886-8301-42bf-93f0-336853e0f96c.png)

Thanks,

**Comment by feraskh0378** [comment] 2022-06-13 11:03
it reproduced only with electron.
when I run my code with chrome it works with no issues.

I am building a windows app using https://www.electronjs.org/docs/latest , typescript  and react , and I am using mathjs from the renderer process as above.

**Comment by josdejong** [comment] 2022-06-14 08:27
So:

> How can we reproduce your issue?

**Comment by gwhitney** [comment] 2022-06-15 18:44
Are you sure you aren't just having a difficulty importing mathjs? Are you sure you have the package installed correctly for it to be found in the electron environment? I ask because at first glance, it seems as though the error is saying that 'evaluate' is undefined...

**Comment by josdejong** [comment] 2022-06-22 13:48
Hard to tell without being able to reproduce the issue.

What you could try is import the bundle, like `import 'mathjs/lib/browser/math.js'`.

**Comment by pramod-bls** [comment] 2023-07-04 19:08
I am having same issue with electron, were you able to solve this?

**Comment by gwhitney** [comment] 2023-07-04 19:16
The difficulty on our end is that as folks who aren't really using electron, it would really help for us to have step-by-step instructions for reproducing this problem from scratch. Thanks.

**Comment by pramod-bls** [comment] 2023-07-04 19:43
fair enough ....

step 1: I create a scope,

```javascript
        if (decaySliceApiCall.isSuccess) {
            const scope = {}
            channels.map((channel) => {
                scope[`Ch${channel}`] = {}
                decays.map((decay) => {
                    scope[`Ch${channel}`][`D${decay}`] = decaySliceApiCall.data.data.z.channels[`${channel}`].decays[`${decay}`]
                })
            })
            setScope(scope)
```

the scope looks like:

<img width="1114" alt="image" src="https://github.com/josdejong/mathjs/assets/126731389/d5841faa-901f-43dd-baa4-a04dbcc53728">

e.g Ch0.D10 is a 2D array of numbers

if I use the expression Ch0.D40./Ch2.D40 ....

```javascript
        if (scope) {
            let localScope = { ...scope }
            try {
                //math.evaluate('fImage=' + expression, localScope).toArray()

                const node = math.parse(expression)
                const code = node.compile()
                console.log(code.evaluate(localScope))
                
            } catch (error) {
                console.error(error);
            }
        }
```
 the outpur is an Error

<img width="1120" alt="image" src="https://github.com/josdejong/mathjs/assets/126731389/f2ac1d00-d9a4-410a-8573-0b6fefc7efbf">

interestingly,

if i change the expression to:

```javascript
const node = math.parse('Ch2.D40')
```

the the output is fine:
<img width="597" alt="image" src="https://github.com/josdejong/mathjs/assets/126731389/ab9b24bd-5d2c-4ef9-a474-b2d32ab0579e">

hope this helps.

**Comment by gwhitney** [comment] 2023-07-04 19:54
This appears to be a different problem than originally posted here, given that you are clearly able to import the mathjs bundle (given the backtraces you are showing), whereas in the original case it seemed  that the import itself was failing in electron. Hence I am moving your question to a separate issue, and will investigate. Thanks.

**Comment by pramod-bls** [comment] 2023-07-04 20:02
Thank you!

--
Pramod Butte, MBBS PhD
CTO
Black Light Surgical Inc.
***@***.******@***.***>
M: 323-481-0133<tel:323-481-0133>



From: Glen Whitney ***@***.***>
Date: Tuesday, July 4, 2023 at 12:54 PM
To: josdejong/mathjs ***@***.***>
Cc: Pramod Butte ***@***.***>, Comment ***@***.***>
Subject: Re: [josdejong/mathjs] TypeError: Cannot read properties of undefined (reading 'evaluate') (Issue #2596)

This appears to be a different problem than originally posted here, given that you are clearly able to import the mathjs bundle (given the backtraces you are showing), whereas in the original case it seemed that the import itself was failing in electron. Hence I am moving your question to a separate issue, and will investigate. Thanks.

**Comment by josdejong** [comment] 2023-07-05 07:45
I'll close this issue now due to lack of information on now to reproduce. Please re-open if there is more information.

One issue that has a different cause is discussed separately in #2990.

**Closed by josdejong** 2023-07-05 07:45 UTC
