### ISSUE TITLE
Adding percentage of previous value

### ISSUE THREAD

**Issue by duprasf** [josdejong/mathjs#304] opened 2015-03-20 18:35 UTC
I was wondering if this feature can be easily added to this already great library. I often have to add a percentage to a value, the strings are usually stored in a database and would look something like this:
"(value)+25%"

When the operation is not using percents, I replace the "(value)" with the value I need and eval it. But I can't use the "+25%" part, I have to change it to 
"(value)*1.25" 

I can then change the "(value)" to the needed value and then run the math.eval() function. The big problem with this approach is that is that is does not always respect the operation order, for example "3+5+10%" should equal 8.8, but "3+5*1.1" equal 8.5.

Also, since I'm not always the one entering those formulas in the database, I can't change the formulas. I was hoping this functionality can be added to the mathjs library. I started to look at the uncompressed code but though it might be easier just to ask you.

**Comment by josdejong** [comment] 2015-03-22 20:24
Having support for percentages would be nice. It's a bit tricky though, as the `%` character is already in use for modulus. 

Maybe we could create percentage as a unit, so you could do something like `value + 25 percent` and/or `value + 25 pct`.

**Comment by duprasf** [comment] 2015-03-24 14:23
I did not think of modulus. Your solution would work, I would only have to regex replace any `%` that are not followed by a digit into `percent` or `pct` depending what you implement before feeding it to `math.eval`.

**Comment by josdejong** [comment] 2015-03-24 15:44
There may be a way to support `%` for both modulus and percentages, I'm not yet sure though. If possible that would be ideal of course :)

**Comment by avianey** [comment] 2016-06-24 09:43
:+1:

**Comment by GoToLoop** [comment] 2016-06-24 14:50
* The modulo operator `%` is binary. That is, it demands 2 operands: `(value)%(value)`
* Something like `(value)+(value)%` is awkward. It's binary as well, but finishes w/ `%`.
* It also means that anything after `%` needs to be another operator, not a (value).
* That is, the expression `100+25%%5` would be parsed as: `100*1.25%5`.
* Operator precedence would be tricky I believe.
* `100%3+25%7%%5` perhaps would be parsed as: `1*1.04%5`? Dunno... guess not.
* The problem is not the postfix `%`, but the middle `+`.  :-(

**Comment by josdejong** [comment] 2016-07-05 18:27
You're right, it's not really doable, will give ambiguities in the expression parser which will lead to nasty situations. 

I will close this issue now, feel free to reopen if anyone has a brilliant idea for a solution :)

**Closed by josdejong** 2016-07-05 18:27 UTC
Labels: feature

**Comment by josdejong** [comment] 2018-11-20 18:46
Thanks for sharing your solution @bornova!

**Comment by stoplion** [comment] 2019-04-20 01:28
@bornova awesome solution.
