### ISSUE TITLE
Converting 1 meV (1 millielectronvolt) returns 1.602176565e-22 meV

### ISSUE THREAD

**Issue by panokhio** [josdejong/mathjs#2894] opened 2023-02-09 19:51 UTC
While writing tests for various units, I noticed that sending in the unit of meV (millielectronvolt) with a value of 1 to convert to a full unit would return "1.602176565e-22 meV" instead of "1 meV". The conversion seems to work for other values just not 1.

**Comment by josdejong** [comment] 2023-02-10 11:16
Thanks for reporting. How can I reproduce what you describe?

**Comment by panokhio** [comment] 2023-02-14 22:06
Look at the result of unit(1, "meV")

**Comment by josdejong** [comment] 2023-02-16 15:49
As far as I see that works normally:

```js
math.unit(1, "meV").toString() // '1 meV'
math.unit(1, "meV").toNumber() // 1
```

You should be careful to not just look at the internal `.value` property, that is a normalized value.

**Comment by gwhitney** [comment] 2023-10-03 00:51
Since there has been no follow-up in over six months and the behavior seems to be as designed, closing.

**Closed by gwhitney** 2023-10-03 00:51 UTC
Labels: Works as intended
