### ISSUE TITLE
TypeError: Cannot set properties of undefined (Complex.prototype) in mathjs after npm install with complex.js 2.2.x

### ISSUE THREAD

**Issue by joyfulkid** [josdejong/mathjs#3277] opened 2024-10-07 08:59 UTC
## Describe the bug
I am using **mathjs 11.12.0** on **Node.js 14.17.0**.  
After running **`npm install`**, I encountered the following error:

```
ERROR Error: Uncaught (in promise): TypeError: Cannot set properties of undefined (setting 'constructor')
TypeError: Cannot set properties of undefined (setting 'constructor')
    at J.isClass (Complex.js:14:21)
```

Upon inspecting the source in the browser's debug mode, I noticed that the **prototype** for `Complex` is `undefined`. The error occurs on the line:

```javascript
Complex.prototype.constructor = Complex;
```

I did not make any changes to the code except running `npm install`, and this error occurred afterward.

To resolve the issue, I explicitly set **`complex.js`** to version **2.1.1**, which fixed the problem. However, I was wondering if it would be possible for **mathjs** to automatically set a compatible version of **complex.js** when it is not explicitly defined, to prevent such issues in the future.

## To Reproduce
1. Install **mathjs 11.12.0** on **Node.js 14.17.0**.
2. Run `npm install` without explicitly defining `complex.js`.
3. Attempt to run any code using `Complex.prototype`.
4. Observe the **TypeError** indicating that `Complex.prototype` is undefined.

## Expected behavior
The code should run without encountering the `TypeError`, and the appropriate `Complex` object should be properly initialized without needing to explicitly set the `complex.js` version.

## Additional context
Explicitly setting **`complex.js`** to **2.1.1** resolved the issue. It would be helpful if `mathjs` automatically installed the appropriate version of `complex.js` to prevent this issue.

If you determine that this issue is not particularly relevant, feel free to close it.  
Thank you!

**Comment by josdejong** [comment] 2024-10-07 09:21
Thanks for reporting. Have you tried with `complex.js@2.2.3`? See https://github.com/rawify/Complex.js/issues/48

**Comment by amininama** [comment] 2024-10-07 13:39
We're also using `mathjs@11.12.0` inside an Angular project. Starting from Friday, we noticed the same issue using 2.2.0:

```
core.mjs:8400 ERROR TypeError: Cannot set properties of undefined (setting 'constructor')
    at push.1637.createComplexClass.isClass (Complex.js:14:32)
    at assertAndCreate (factory.js:35:12)
    at 33158 (pureFunctionsAny.generated.js:12:55)
    at __webpack_require__ (bootstrap:19:1)
    at 91623 (qmos-dynamic-layout.mjs:159:1)
    at __webpack_require__ (bootstrap:19:1)
    at 4870 (qmos-product-code-selector.mjs:624:1)
    at __webpack_require__ (bootstrap:19:1)
    at 73405 (index.ts:2:57)
    at __webpack_require__ (bootstrap:19:1)
```

 

After moving to version: `2.2.3`, the problem persists.

**Comment by infusion** [comment] 2024-10-07 14:05
The question is if the CJS or ESM version is used, causing the problem on this kind of dated node.js installation.

Could you do me a favor please and add a `console.log` to `node_modules/Complex.js/dist/complex.js` and `node_modules/Complex.js/dist/complex.mjs` to see what version your system is using? And also a `console.log(Complex)` at the place of your `Complex.prototype.constructor = Complex;` would be helpful, what is actually in there.

Sorry for the trouble, my libs (including the ones used by math.js) were modernized recently and producing some hickups here and there when it comes to supporting all platforms while being future proof.

**Comment by WangGuan11** [comment] 2024-10-08 10:34
如何指定Complex 版本？我在mathjs里的源码看到是2.1.1，但是 在 node_modules 里的 Complex看到的是 2.2.3

**Comment by josdejong** [comment] 2024-10-08 13:36
@infusion the stacktraces in https://github.com/josdejong/mathjs/issues/3279#issue-2572526838 and https://github.com/rawify/Complex.js/issues/48#issuecomment-2398977341 give a clue: ESM is used with Webpack, though I don't know yet what version of Webpack.

**Comment by josdejong** [comment] 2024-10-08 14:01
You can use an older version of `mathjs`, the necessary part is `"complex.js": "2.1.1"`

**Comment by WangGuan11** [comment] 2024-10-08 14:02
> You can use an older version of `mathjs`, the necessary part is `"complex.js": "2.1.1"`

i try

**Comment by WangGuan11** [comment] 2024-10-08 14:10
> > You can use an older version of `mathjs`, the necessary part is `"complex.js": "2.1.1"`
> 
> i try


    "mathjs": "11.12.0",
    "complex.js": "2.1.1",

it's OK

**Comment by amininama** [comment] 2024-10-08 14:46
> We're also using `mathjs@11.12.0` inside an Angular project. Starting from Friday, we noticed the same issue using 2.2.0:
> 
> ```
> core.mjs:8400 ERROR TypeError: Cannot set properties of undefined (setting 'constructor')
>     at push.1637.createComplexClass.isClass (Complex.js:14:32)
>     at assertAndCreate (factory.js:35:12)
>     at 33158 (pureFunctionsAny.generated.js:12:55)
>     at __webpack_require__ (bootstrap:19:1)
>     at 91623 (qmos-dynamic-layout.mjs:159:1)
>     at __webpack_require__ (bootstrap:19:1)
>     at 4870 (qmos-product-code-selector.mjs:624:1)
>     at __webpack_require__ (bootstrap:19:1)
>     at 73405 (index.ts:2:57)
>     at __webpack_require__ (bootstrap:19:1)
> ```
> 
> After moving to version: `2.2.3`, the problem persists.

More insights:
In our existing project, I can see that in `node_modules/mathjs/lib/esm/type/complex/Complex.js`, The code is trying to set `Complex.prototype.constructor` which Complex is an object with the following structure:
{name: 'Complex', Complex: f}
While `Complex.prototype` is undefined, I can see that `Complex.Complex.prototype` exists.

In regards to compile-type (ESM vs CJS), I can confirm that in `package.json` of the project, the type is set to "module" and also in `tsconfig.json`, the module is set to "es2020". And we're using webpack@5.76.1.

Regarding the initializer of Complex, I added `console.log`s to the constructors of both `Complex.js` and `Complex.mjs` but none of them log anything. judging from chrome's devtools, looks like it's coming from `Complex.min.js`:
[[FunctionalLocation]]: complex.min.js:8

I tried to create an isolated Angular15 with the sole dependency to mathjs. The project runs flawlessly using `complex.js@2.2.3`. So, there has to be an issue within the structure of our existing code that causes this.

**Comment by josdejong** [comment] 2024-10-08 15:28
Thanks a lot @amininama, this helps.

@infusion I think the issue is caused by the `"browser": "complex.min.js"` field in `package.json`. According to the following thread, Webpack uses the `browser` field as first when it exists, but that's containing CommonJS and gives issues in an ESM environment. The solution presented [here](https://github.com/webpack/webpack/issues/4674#issuecomment-355853969) may work. But maybe it's better to not have the `browser` field at all? As far as I understand it, the field "browser" is deprecated in favor of "exports".

**Comment by infusion** [comment] 2024-10-08 15:55
Could those facing this issue please test this verdict? Could you just drop the "browser" line in `node_modules/complex.js/package.json`?

**Comment by infusion** [comment] 2024-10-08 18:05
After a report on the complex.js issue tracker indicated that Jos might be right, I published 2.2.4 without the browser entry in package.json. Please test the new version.

**Comment by amininama** [comment] 2024-10-08 19:05
Thanks guys!
Just for the record, `mathjs@11.12.0` along with `Complex.js@2.2.4` work perfectly for us.

**Comment by josdejong** [comment] 2024-10-09 06:51
Good to hear that `complex.js@2.2.4` solves the issue! I'll close this issue now.

**Closed by josdejong** 2024-10-09 06:51 UTC
Labels: bug
