### ISSUE TITLE
Lib/expression/docs disappears on npm

### ISSUE THREAD

**Issue by albertbuchard** [josdejong/mathjs#809] opened 2017-03-16 19:40 UTC
The 'lib/expression/docs' folder disapears on the repo published on npm. I also tried to publish a forked repo, same problem. I don't know if it is on purpose or not, I could not find any trace of an ignore for it in .npmignor or gitignore.

The problem arises when trying to `require('mathjs')`, you get this error:

```
/Users/Pro/Google Drive/dev/javascript/experiment-boxes/node_modules/mathjs/lib/expression/index.js
Cannot find module './docs'
...
```

I am probably missing something, any clues to help me ?

**Comment by josdejong** [comment] 2017-03-19 09:04
Thanks for reporting. 

I can't reproduce your issue on my machine, and for example exploring the npm package via unpkg shows the docs folder is still there:

https://unpkg.com/mathjs@3.10.0/lib/expression/docs/

Could it be that your local npm cache is corrupted somehow?

**Comment by BobbyWibowo** [comment] 2017-06-07 02:37
I also kept on getting this with yarn. No matter how many times I cleared its cache and then reinstalled everything, that path in particular would never be downloaded. It behaved the same on both my VPS (CentOS) and my PC (Windows 10). I have also tried using this Git itself (master), but that particular path wouldn't be downloaded either.

**Comment by josdejong** [comment] 2017-06-08 17:54
@BobbyWibowo thanks for reporting. Are you sure you're looking at the right place? 

The path is just there on github: https://github.com/josdejong/mathjs/tree/master/lib/expression/docs
and on npm: https://unpkg.com/mathjs@3.13.3/lib/expression/docs/

I've also checked again by installing mathjs via npm and yarn on both a Linux and a Windows machine, and these folders are just there as far as I can see.

**Comment by BobbyWibowo** [comment] 2017-07-18 22:40
So I just tried it again a couple minutes ago with yarn `0.27.5`.
I'm not sure why, but it seems to be intentionally ignoring all `docs` directories? `docs` in the root directory doesn't exist in `../node_modules/mathjs/` either after adding the package. It's also ignoring `test` and `examples` (which I assume are indeed as designed, though). Anyways, I'm guessing that's why it's also ignoring `docs` in `lib/expression/`?

**Comment by BobbyWibowo** [comment] 2017-07-18 22:41
Oh, wait a second. It seems to be working fine if I were to use `yarn add mathjs`, but it goes nuts if I simply add it to my project's `package.json` then do `yarn install`...

**Comment by BobbyWibowo** [comment] 2017-07-18 22:51
Tsk, I found the cause. There was a `.yarnclean` file on my project and `docs` was written in it.

**Comment by josdejong** [comment] 2017-07-19 08:41
ah, that explains it. Thanks for reporting back, will close this issue now.

**Closed by josdejong** 2017-07-19 08:41 UTC
