### ISSUE TITLE
(Multi)set operations

### ISSUE THREAD

**Issue by Nekomajin42** [josdejong/mathjs#696] opened 2016-07-28 21:57 UTC
Hi guys!

While I was working with the library, I was missing the set operations. I started to implement them, for now as an experiment. I have the following operations implemented (all of them working with multisets too):
- `setUnion`: Returns the union of two sets as an array.
- `setIntersect`: Returns the intersection of two sets as an array.
- `setDifference`: Returns the difference of two sets as an array.
- `setSymDifference`: Returns the symmetric difference of two sets as an array.
- `setCartesian`: Returns the cartesian product of two arrays as a matrix.
- `setSize`: Returns the size of the array as a number. (If a second `true` parameter is passed, it returns only the number of unique elements.)
- `setIsSubset`: Returns `true` if the first array is a subset of the second array. Otherwise returns `false`.
- `setPowerset`: Returns the powerset of a set as a matrix.

Would you think it's a useful addition to the library?

Now I have these in a separate "set" folder, and for now, they work only with 1D arrays. Should I add them to the "matrix" folder and make them work with matrices too?

And I've ran into a problem. In the scripts, I return arrays (apart from the size and subset operations), but the `eval` function does not seem to output an array. For example:

`a = [1, 2, 3, 4]`
`b = [3, 4]`
`parser.eval(setDifference(a, b)).toString()` should return `[1, 2]`, but instead it returns `1,2`. It seems like it's treated as string, doesn't it? What could be the problem?

**Comment by josdejong** [comment] 2016-08-01 19:09
That sounds certainly interesting. We could group these functions under a new category 'set', like you've already done. They should indeed work with matrices too. We could think about what the functions should do with 2D matrices or multidimensional: maybe just handle the contents element wise (just flatten the contents and find the union/intersect/diff).

You can do `math.format(parser.eval(setDifference(a, b)))` instead of `.toString()` on your Array output.

**Comment by Nekomajin42** [comment] 2016-08-01 19:33
Do flattening mean "removing the dimensions" and handle any matrix like it was a simple array? If so, I think it is a good solution.

About the other thing, the problem is I use the `.toString()` method on the evaluated output, because I immediately parse the output too, to apply the formatting (`.toHTML()`). And it's strange, because if I define an array like a regular variable, it works fine. Am I doing something wrong in the set functions? You can see the sources here: https://github.com/Nekomajin42/mathjs/tree/master/lib/function/set

**Comment by josdejong** [comment] 2016-08-01 19:45
> Do flattening mean "removing the dimensions" and handle any matrix like it was a simple array? If so, I think it is a good solution.

Yes that's what I meant, there are already functions for that in mathjs.

I'm not sure what the problem is with `toString`, it's simply how the `toString` of an JavaScript array works: `[1,2,3].toString()` simply returns `1,2,3`. The `math.format` function stringifies Arrays and Matrices *with* brackets.

Your code looks nice and clean so far!

**Comment by Nekomajin42** [comment] 2016-08-01 19:57
OK, I guess I understand what you mean. I will try to solve this problem, implement the methods to matrices, then give you an update. Thanks!

**Comment by Nekomajin42** [comment] 2016-08-01 20:00
One more thing. Do you think it would be better to implement a separate `setUniqueSize` method instead of the optional second parameter stuff?

**Comment by josdejong** [comment] 2016-08-01 20:06
I'm not sure whether `setSize` is needed at all, we already have the function `size`. A new function `unique` to count the number of unique elements will be useful though.

I was thinking, the prefix `set*` is logic, but maybe confused with getter/setter functions. I haven't yet come up with alternative naming though.

**Comment by Nekomajin42** [comment] 2016-08-01 20:20
Yes, it is a bit confusing, especially with the `setSize` method, but it's the term, so I think we should go with it.

On the other hand, `setSize` is indeed redundant, but if someone wants to work with sets, it might be strange to look for the `size` method in the matrix operations. I think we should keep it as an alias, if it does not cause any trouble.

**Comment by josdejong** [comment] 2016-08-01 20:23
ehm, yeah, but even more ideally, these set functions should just fit seamlessly in mathjs and not be some special, isolated sub section.

**Comment by Nekomajin42** [comment] 2016-08-01 20:38
It is also true. I choose to use the prefix, because there is an `intersect` function for points and lines. I don't know how we could generalize that function, because the same term is used for different operations. Plus the `difference` name could be misleading, because it's similar to the `subtract` operation.

However, we could loose the prefix, but these are special operations with a special data type (even if it is an array in the implementation), and can not be used with simple numbers.

**Comment by josdejong** [comment] 2016-08-02 18:28
Yes, it's indeed tricky because we already have `intersect`.

**Comment by Nekomajin42** [comment] 2016-08-08 20:30
Can I create a separate file somewhere to store two helper functions for multiset operations? To differentiate between identical values, I have to assign an identifier to every value. Then I have to remove those before I return the result of the operation. Now I have the same code in many files, which is not ideal.

The function `identify` accetps an array, and returns an object. From `[1, 1, 2]` it creates `[{value: 1, identifier: 0}, {value: 1, identifier: 1}, {value: 2, identifier: 0}]`. The function `generalize` removes the identifiers, and returns the values in a single array.

I think, it can be helpful in other cases, but it would be helpful for me for sure.

---

Another issue: when I run `npm run docs`, as it is stated [here](https://github.com/josdejong/mathjs/blob/master/misc/how_to_publish.md#build-library), I get the following error:

    F:\Web\mathjs\tools\docgenerator.js:184
      if (doc.examples[doc.examples.length - 1].trim() == '') doc.examples.pop();
                                               ^

    TypeError: Cannot read property 'trim' of undefined
    at parseExamples (F:\Web\mathjs\tools\docgenerator.js:184:48)
    at generateDoc (F:\Web\mathjs\tools\docgenerator.js:302:9)
    at F:\Web\mathjs\tools\docgenerator.js:518:33
    at f (F:\Web\mathjs\node_modules\once\once.js:17:25)
    at Glob.<anonymous> (F:\Web\mathjs\node_modules\glob\glob.js:146:7)
    at emitOne (events.js:96:13)
    at Glob.emit (events.js:188:7)
    at Glob._finish (F:\Web\mathjs\node_modules\glob\glob.js:194:8)
    at done (F:\Web\mathjs\node_modules\glob\glob.js:179:14)
    at Glob._processGlobStar2 (F:\Web\mathjs\node_modules\glob\glob.js:631:12)

**Comment by josdejong** [comment] 2016-08-09 18:33
> Can I create a separate file somewhere to store two helper functions for multiset operations?

Yes, sure, this is already done a lot throughout the library.

> Another issue: when I run npm run docs, as it is stated here, I get the following error

The script to generate docs expects the header comment of a function to be in some specific form (look at existing functions to see what sort of structure is expected). Don't worry to much here, I can have a look what's going wrong if issue this remains (could also be an issue in the docs script).

**Comment by Nekomajin42** [comment] 2016-08-10 22:41
I am about to send a pull request, but I can't because of a validation error. It happens because of the doc generator error. What should I do?

**Comment by josdejong** [comment] 2016-08-14 11:51
Can I have a look at your work so far? It's not a big deal when the doc generator still give an error, I can fix that afterwards. I expect this will be easy to fix.

**Comment by Nekomajin42** [comment] 2016-08-15 16:23
Here are the necessary files: https://github.com/Nekomajin42/mathjs-lib

**Comment by josdejong** [comment] 2016-08-15 19:20
Thanks. I found the reason why the doc generator gives an error: it couldn't parse the examples in your functions since it expects an indentation of 3 or 4 spaces, whilst your code uses tabs there. So it should be fixed when you replace the tabs with spaces. Besides that I've made the docgenerator robust against this (see https://github.com/josdejong/mathjs/commit/e0095229ac840f92166248597d5bcf156b9fddb5).

**Comment by Nekomajin42** [comment] 2016-08-15 20:16
*doh*

It is hard for me to adjust to the Node.js syntax style, because my style is very different.  I will change them ASAP, and send the PR.

**Comment by josdejong** [comment] 2016-08-17 19:41
ha ha that can happen.

**Comment by josdejong** [comment] 2019-12-03 21:24
I think we forgot to close this issue, the functions are already implemented long time ago.

**Closed by josdejong** 2019-12-03 21:24 UTC
Labels: feature
