### ISSUE TITLE
Euler number sometimes returns "Undefined"

### ISSUE THREAD

**Issue by gang65** [josdejong/mathjs#505] opened 2015-11-15 02:04 UTC
Hello Jos.

Euler number sometimes returns "Undefined".
It is not happen very often (Once per 15 times), but it is happen.

How to reproduce:
1. Take my QML script and change shortFormula to:
           var shortFormula = "log(E)";
2. Now run script 20 times.
3. After few runs you will receive error:
  qmlscene hello.qml
file:///home/kosiorek/Desktop/hello-bignumber-euler-number/math.js:33727: TypeError: Type error

Could you please take a look at this?

Thanks in advance

**Comment by gang65** [comment] 2015-11-15 02:19
I attached QML script into bug report:
https://bugs.launchpad.net/ubuntu-calculator-app/+bug/1467316

**Comment by josdejong** [comment] 2015-11-15 10:04
Thanks for reporting this issue, let's continue the discussion in https://bugs.launchpad.net/ubuntu-calculator-app/+bug/1467316.

**Comment by gang65** [comment] 2015-11-19 06:30
Hello Jos.
Just wondering, if you manage to reproduce that bug?
According to Marco (from launchpad), he was able to reproduce that bug with following script:

Reproduced by clicking the text and closing 20 times:
$ for i in {1..20};do qmlscene hello.qml;done
file:///tmp/hello-bignumber-euler-number/math.js:33727: TypeError: Type error

Thanks for your great job!

**Comment by josdejong** [comment] 2015-11-19 08:04
ah sorry, I wasn't aware that the bug tracker doesn't send notifications, hadn't seen your replies.

**Comment by gang65** [comment] 2015-11-28 21:48
Hello Jos.
How can I help resolving this issue?

**Comment by josdejong** [comment] 2015-11-29 14:37
You can help by debugging it yourself, no need to wait for me or something. At least you guys seem to be able to (sometimes) reproduce the bug...

I mentioned two problems in the [launchpad bug](https://bugs.launchpad.net/ubuntu-calculator-app/+bug/1467316) that I came across whilst trying to reproduce this bug, these needs to be resolved first before I can even *try* to debug the bug itself. I have zero knowledge about Qt stuff and have no clue how to proceed, not being able to execute your code example nor being able to reproduce the bug.

As this bug seems to occur only randomly when restarting the process x times, there is some race condition going on causing this to happen only sometimes. As math.js is just a synchronous piece of JS code which cannot have race conditions, it's likely that the problem is not in the JavaScript code itself but in the underlying JavaScript engine. If the bug would be in the JavaScript itself, it should occur consistently, not randomly. This may be a hard nut to crack.

**Comment by josdejong** [comment] 2015-12-21 10:31
@gang65 no news on this issue?

**Comment by gang65** [comment] 2015-12-21 14:28
Unfortunately I haven't look at this issue.
I will try to run some Debugger (QtCreator), and compare variables values.

**Comment by josdejong** [comment] 2015-12-22 08:24
Maybe also try the latest version of Qt like I used (not being able to reproduce the issue)

**Comment by josdejong** [comment] 2019-03-28 19:03
Will close this old topic now. Feel free to reopen if still an issue.

**Closed by josdejong** 2019-03-28 19:03 UTC
