### ISSUE TITLE
Type definition missing for `hasNumericValue`

### ISSUE THREAD

**Issue by Shawnfoto** [josdejong/mathjs#2271] opened 2021-07-01 00:36 UTC
I'm not sure is it a bug or another thing I made mistake,
I used hasNumericValue in NodeJS with ES6 module, it will error for me, but CommonJS can be work.

```js
// const { round, hasNumericValue } = require('mathjs')
import { round, hasNumericValue } from 'mathjs';
```

![bug](https://user-images.githubusercontent.com/18244561/124047643-7f295080-d9c9-11eb-8ebe-c4eb4b5c2699.png)

**Comment by m93a** [comment] 2021-07-01 00:49
Hey Shawn,
thanks for reporting the bug! The problem is caused by `hasNumericValue` not being in the [type declarations file](https://github.com/josdejong/mathjs/blob/develop/types/index.d.ts). If you compile the code and run it, it will actually work fine, it's the TypeScript checker that throws the error. Before the bug is fixed, you can use this walkaround:
```typescript
import math from 'mathjs';
const hasNumericValue = (math as any).hasNumericValue;
```

However, fixing the bug should be relatively easy. If anyone wants to fix this, PRs are welcome :)

**Comment by thunder-coding** [comment] 2021-09-27 08:12
If this issue is fixed, can we close it. Also there is a new release after this commit 🙃

**Comment by josdejong** [comment] 2021-09-27 20:05
Ah, good point, will close this issue.

**Closed by josdejong** 2021-09-27 20:05 UTC
Labels: bug, help wanted, typescript
