### ISSUE TITLE
math.median(A) mutates A 

### ISSUE THREAD

**Issue by mrtns** [josdejong/mathjs#309] opened 2015-03-26 07:50 UTC
Given an array `a`:

    > var a = [3,2,1];

    > a
    < [3, 2, 1]

When `mean` is called:

    > mathjs.mean(a);
    < 2

the sort order of `a` is preserved:

    > a
    < [3, 2, 1]

However, when `median` is called:

    > mathjs.median(a);
    < 2

the sort order of `a` is lost. `a` is mutated, and is now sorted ascending:

    > a
    < [1, 2, 3]

It this expected behaviour? If not, I can provide a PR with failing test. Thanks!

**Comment by josdejong** [comment] 2015-03-26 08:09
Thanks, non of the functions of math.js should mutate the inputs, this is not intended behavior. 

If you can provide a fix for this would be great, thanks.

**Comment by josdejong** [comment] 2015-03-26 08:09
And preferably an extra unit test to prevent any regression in the future...

**Comment by FSMaxB** [comment] 2015-04-25 22:09
This bug is fixed in the `develop` branch.

**Comment by josdejong** [comment] 2015-04-26 11:21
Thanks Max. I've updated the HISTORY.md file accordingly

**Comment by josdejong** [comment] 2015-05-31 18:03
This is now fixed in v1.7.0

**Closed by josdejong** 2015-05-31 18:03 UTC
