### ISSUE TITLE
Hardware acceleration for matrix operations

### ISSUE THREAD

**Issue by jarble** [josdejong/mathjs#1788] opened 2020-03-27 18:21 UTC
To improve the efficiency of matrix operations, MathJS could run some of these operations on the GPU instead of the CPU. This could be useful when adding, subtracting, or multiplying very large matrices.

Would it be possible to do this using a hardware acceleration library like [GPU.js](https://gpu.rocks/)?

**Comment by josdejong** [comment] 2020-03-29 08:17
Thanks for your suggestion @jarble . Hardware acceleration would be cool, but I expect that this is too specific to easily integrate with mathjs. I have the feeling that to make that work, you have to start from the GPU and build an API from there (lie GPU.js), instead of the other way around. I may be mistaken though. So a challenge here: if someone has a concrete idea of how this would/could work out, let's keep this issue open.

**Comment by moulay-idris** [comment] 2020-04-12 19:37
I suggested to run arithmetic code into a Web Worker ?

https://developer.mozilla.org/fr/docs/Web/API/Web_Workers_API/Utilisation_des_web_workers.

**Comment by josdejong** [comment] 2020-04-13 15:46
Yes, that's always a possibility :)

**Comment by mightypenguin** [comment] 2020-06-15 15:53
Webworkers are a good start, they let you run multiple threads of logic at the same time.
But I still think that that we'd see massive improvement and usage by allowing even a subset of operations to use another library like GPU.js.
Probably would require a trade study example of some kind to see what the wins are.

The main issue I see is that if math.js doesn't GPU accel, than another project will, and it will probably get most of the potential user base of math.js.

Probably most of the people needing to do serious math will need/want accel.
1. Webworkers (first / easiest step to improve performance)
2. GPU ( holy grail )

**Comment by gwhitney** [comment] 2023-10-06 01:20
Duplicate of #2702. Closing this -- please hold further discussion there.

**Closed by gwhitney** 2023-10-06 01:21 UTC
Labels: feature
