### ISSUE TITLE
`math.subset` converts matrix to scalar

### ISSUE THREAD

**Issue by DbCrWk** [josdejong/mathjs#1484] opened 2019-04-23 02:47 UTC
First, this is a great package!

One small quirk that I've noticed is that if I do something like:
```javascript
const matrix = [[1, 0], [0, 1]];
const expectedSubMatrix = [[ 1 ]]; // this is a 1-by-1 matrix

const upperElement = math.range(0, 0);
const actualSubMatrix = math.subset(matrix, math.index(upperElement, upperElement));
// actualSubMatrix is the scalar/number 1, rather than a 1-by-1-matrix
```

Is this an intentional casting of a `1`-by-`1` matrix into a scalar? If so, is there a way to enforce that pulling the subset of a matrix always returns a matrix?

(For my particular use case, I have a function that accepts an arbitrary index `k` and returns the `k`-by-`k` upper left submatrix. Therefore, to get around this quirk, I have to special case the situation when the passed `k` value is `1`.)

@pdeaville

**Comment by josdejong** [comment] 2019-04-23 19:53
Thanks @DbCrWk, great to hear you like the library :)

Changing 1x1 output of a matrix subset is indeed intentional. When retrieving a single value from a matrix, often you want to continue working with it as being a scalar. 

There is currently no way to enforce output being kept a matrix. We could consider making this possible for example by configuring `predictable: true` globally, or passing this as an extra option to `subset`.

What you could do for now is create a small wrapper around `math.subset` which checks if the output returned by `math.subset` is a scalar and if so, turn it into a 1x1 Matrix again and return that.

**Comment by DbCrWk** [comment] 2019-04-24 04:47
Good to know. I have a wrapper written around it for now. If you're good with some parameter being passed (or equivalent), I can open a PR on this!

**Comment by josdejong** [comment] 2019-04-28 14:17
Thanks for your offer Dev. I'm still a bit in doubt about what would be the best approach here: passing an option along with `subset`, or using the global option `predictable` for this. I think I have a slight preference for using a global option for this, since inside the editor you use bracket notations like `c = A[1, 2]`, which under the hood uses `subset`, but there is no way to pass an option there.

**Comment by DbCrWk** [comment] 2019-04-29 02:09
Sounds good! I'll take a crack at it.

**Comment by josdejong** [comment] 2019-04-29 06:21
Cool, thanks!

This will be a breaking change so we have to schedule when to release.

@DbCrWk can you please work from the `modular_architecture` branch instead of `develop`? That will save us some merge conflicts. We're about to release a large, breaking refactor of mathjs, which for example has a different dependency injection mechanism. See #71.

**Comment by DbCrWk** [comment] 2019-04-30 00:08
Cool, will do

**Comment by josdejong** [comment] 2019-05-02 18:56
Dev, I've just merged `modular_architecture` into `develop`, so please continue any work there again.

**Comment by gwhitney** [comment] 2023-10-06 04:06
Closing as duplicate of #2344.

**Closed by gwhitney** 2023-10-06 04:06 UTC
