### ISSUE TITLE
SyntaxError: In "GeV^-2", "^" must be followed by a floating-point number

### ISSUE THREAD

**Issue by 2018Cool** [josdejong/mathjs#2086] opened 2021-01-19 05:28 UTC
Version： 8.1.1
Code：
import { fraction, multiply, format } from 'mathjs'
const  transfer_amount= +format(multiply(fraction(this.acceptForm.transferAmount), fraction(PAYMENT_CONVERSION)), { fraction: 'decimal' })

**Comment by wangkangfeng** [comment] 2021-01-20 08:56
Going back to 8.1.0 fixed it for us.

**Comment by josdejong** [comment] 2021-01-20 12:51
Thanks for reporting. How can I reproduce this issue?

**Comment by lssdo12** [comment] 2021-04-21 08:55
Going back to 8.1.0
modify package.json:
"mathjs": "8.1.0"

**Comment by josdejong** [comment] 2021-04-21 11:28
@lssdo12 how can I reproduce this issue?

**Comment by m93a** [comment] 2021-07-01 01:50
Closing as "cannot reproduce".

**Closed** 2021-07-01 01:49 UTC

**Comment by CaledoniaProject** [comment] 2021-08-15 08:25
Same error in 9.4.4

**Comment by lssdo12** [comment] 2021-08-15 08:36
> @lssdo12 how can I reproduce this issue?

import mathjs can produce that

**Comment by CaledoniaProject** [comment] 2021-08-15 09:39
@josdejong Please reopen and investigate this issue. The stack above should be helpful to you

**Comment by m93a** [comment] 2021-08-15 10:11
Please provide specific steps so that we can reproduce the error. So far you haven't provided any useful information.

The code in OP works without a problem.

![image](https://user-images.githubusercontent.com/1671665/129474952-c7d15a20-24f1-4919-9e67-3789864c70f0.png)

**Comment by CaledoniaProject** [comment] 2021-08-15 12:16
The only thing I did in VUE is

```
import { evaluate } from 'mathjs'
...

methods: xxx() {
   return evaluate(xxxxx)
}
```

**Comment by CaledoniaProject** [comment] 2021-08-15 12:29
Hmm, looks like a babel or math expression evaluator version issue

[8.1.0-8.1.1.diff.txt](https://github.com/josdejong/mathjs/files/6988119/8.1.0-8.1.1.diff.txt)

**Comment by m93a** [comment] 2021-08-15 17:07
I've created a new Vue project, imported `evaluate` and run it. I've tried running it  Everything works as expected for me, no error or anything. Here's my repo: https://github.com/m93a/mathjs-vue-test

Could you try to create a minimal repo that reproduces this issue?

**Comment by mydansun** [comment] 2022-06-29 07:00
2022-06-29 still has the same problem

**Comment by josdejong** [comment] 2022-06-29 08:18
@mydansun thanks for reporting. How can we reproduce this issue exactly? So far we have no clue how to reproduce it.

**Comment by ackemaneva** [comment] 2022-08-27 07:18
hello， i find the same problem at 2022-08-27，can you provide solutions for this problem？thank u.
here is package.json of my vue project.
![image](https://user-images.githubusercontent.com/17824405/187019369-380a3b15-3148-4cda-beab-404f9cecb590.png)
i had use mathjs for ```8.1.0```, but it has no effect.

here is my util function that use mathjs
```
import { create, all } from 'mathjs'
const config = {
  number: 'BigNumber',
  precision: 20
}
const math = create(all, config);
export default {
  //开方
  numberSqrt: function (arg1) {
    return math.sqrt(arg1)
  },
  //除
  numberExcept: function (arg1, arg2) {
    return arg2 == 0 ? 0 : math.divide(arg1, arg2)
  },
  //乘
  numberRide: function (arg1, arg2) {
    return math.multiply(arg1, arg2);
  },
  //加
  numberAdd: function (arg1, arg2) {
    return math.add(arg1, arg2);
  },
  //减
  numberSub: function (arg1, arg2) {
    return math.subtract(arg1, arg2);
  }
}
```
when i use this util on dev enviroment,it's right;but if build for production enviroment,it's error.
![image](https://user-images.githubusercontent.com/17824405/187019565-dfdd5a9c-90da-440d-99dd-1a8338be6633.png)

**Comment by josdejong** [comment] 2022-08-30 15:53
Is this also an issue in the latest version of mathjs, `v11.1.0`? If so, can you provide a minimal way to reproduce the issue?

**Comment by lokialone** [comment] 2023-09-06 11:59
have the same promble @11.10.0,

![image](https://github.com/josdejong/mathjs/assets/5095713/b6167e55-bfb7-48d5-ba04-3fa4bf18cec9)

**Comment by josdejong** [comment] 2023-09-06 13:33
Thanks for reporting @lokialone . How can I reproduce this issue? 

My guess is that you're using a unicode dash character that looks like the minus symbol `-`.

**Comment by Tishinator** [comment] 2024-02-23 22:23
Getting the same issue with 12.3.1
Using VueJs 

Works fine with no errors if I run my project through 'npm run dev' but when I run my project through 'npm run build' I get the error.

Here's how the code is being used:
`
import * as math from 'mathjs';
`

all we're using is the math.evaluate function. Works fine in dev.

**Comment by Tishinator** [comment] 2024-02-23 22:43
Update:
Downgraded the version to 8.1.0 as others suggested and it seems to resolve the issue.

might want to look into the version differences there.

**Comment by dvd101x** [comment] 2024-02-24 04:46
Tried to replicate by:
- using vue 3.4.15
- using mathjs 12.4.0

Importing mathjs as:

```js
import {create, all} from 'mathjs'
const math = create(all)
```
Running 
```js
math.evaluate("GeV^-2")
```

No issues either in `npm run dev` or `npm run build`

Also tried importing mathjs as stated (I think it's not recommended):
```js
import * as math from 'mathjs'
```

Still no issues either in `npm run dev` or `npm run build`

@Tishinator do you have more information that could be useful to replicate this issue?

**Comment by Tishinator** [comment] 2024-02-25 22:23
```
"dependencies": {
    "@ag-grid-community/all-modules": "^24.0.0",
    "@ag-grid-community/core": "^24.0.0",
    "@ag-grid-community/vue": "^24.0.0",
    "@fortawesome/fontawesome": "^1.1.8",
    "@fortawesome/fontawesome-free": "^5.12.0",
    "@fortawesome/fontawesome-free-regular": "^5.0.13",
    "@fortawesome/fontawesome-svg-core": "^1.2.26",
    "@fortawesome/free-brands-svg-icons": "^5.15.4",
    "@fortawesome/free-regular-svg-icons": "^5.15.4",
    "@fortawesome/free-solid-svg-icons": "^5.15.4",
    "@fortawesome/vue-fontawesome": "^2.0.8",
    "bootstrap": "^4.6.2",
    "bootstrap-vue": "^2.22.0",
    "fancy-log": "^1.3.3",
    "jquery": "^3.6.1",
    "lodash": "^4.17.21",
    "mathjs": "^12.3.1",
    "moment": "^2.29.4",
    "router": "^1.3.7",
    "vue": "^2.5.2",
    "vue-bootstrap-typeahead": "^0.2.6",
    "vue-class-component": "^7.2.6",
    "vue-flatpickr-component": "^7.0.3",
    "vue-fontawesome": "0.0.2",
    "vue-form-wizard": "^0.8.4",
    "vue-js-modal": "^1.3.35",
    "vue-plotly": "^1.1.0",
    "vue-property-decorator": "^8.5.1",
    "vue-resource": "^1.5.3",
    "vue-router": "^3.6.5",
    "vuedraggable": "^2.23.2",
    "vuejs-dialog": "^1.4.1",
    "vuex": "^3.1.2"
  },
  "devDependencies": {
    "autoprefixer": "^7.1.2",
    "babel-core": "^6.22.1",
    "babel-helper-vue-jsx-merge-props": "^2.0.3",
    "babel-loader": "^7.1.1",
    "babel-plugin-syntax-jsx": "^6.18.0",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-plugin-transform-vue-jsx": "^3.5.0",
    "babel-preset-env": "^1.3.2",
    "babel-preset-stage-2": "^6.22.0",
    "chalk": "^2.0.1",
    "copy-webpack-plugin": "^4.0.1",
    "copyfiles": "^2.4.1",
    "css-loader": "^0.28.0",
    "extract-text-webpack-plugin": "^3.0.0",
    "file-loader": "^1.1.4",
    "friendly-errors-webpack-plugin": "^1.6.1",
    "html-webpack-plugin": "^2.30.1",
    "node-notifier": "^5.1.2",
    "optimize-css-assets-webpack-plugin": "^3.2.0",
    "ora": "^1.2.0",
    "portfinder": "^1.0.13",
    "postcss-import": "^11.0.0",
    "postcss-loader": "^2.0.8",
    "postcss-url": "^7.2.1",
    "rimraf": "^2.7.1",
    "semver": "^5.3.0",
    "shelljs": "^0.7.6",
    "uglifyjs-webpack-plugin": "^1.1.1",
    "url-loader": "^0.5.8",
    "vue-loader": "^13.3.0",
    "vue-style-loader": "^3.0.1",
    "vue-template-compiler": "^2.5.2",
    "webpack": "^3.6.0",
    "webpack-bundle-analyzer": "^2.9.0",
    "webpack-dev-server": "^2.11.5",
    "webpack-merge": "^4.1.0"
  },
```
  
  
  Here's the extremely simplified version of what im working with:
  (ive tested with this code and got the same results)
        
```
            // yards to inches
            let value = 3
            let equation = "value * 1296.0";

            const scope = {
                value : value
            }
            this.thisNum = math.evaluate(equation, scope)
```


Works on 8.1.0, Works on dev, Fails on live (build)

**Comment by josdejong** [comment] 2024-02-28 09:19
@Tishinator is it possible to share a (minimal) git repo that demonstrates the issue? Since we've trouble replicating the issue on our side.

**Comment by Tishinator** [comment] 2024-02-28 15:07
unfortunately for work reasons i cannot. but I will  try and build a new project from home when i get the change on a smaller scale.
