### ISSUE TITLE
isUnit check?

### ISSUE THREAD

**Issue by stoplion** [josdejong/mathjs#1257] opened 2018-09-19 00:14 UTC
Since unit is multiply Node with a ConstantNode and SymbolNode. Have to check the args[1] each time to see if a node is unit. I read in other Issues mention of `isUnit` property. Is that currently available? If not, is there a preferred way to check if a node is a unit?

**Comment by josdejong** [comment] 2018-09-19 07:03
Hm, there is an `isUnit` function but it's a bit hidden under `math.type.isUnit`. 

Makes sense to move these functions to the main `math` namespace instead

**Comment by josdejong** [comment] 2018-09-19 07:04
Duplicate of #627, let's continue the discussion there.

**Closed by josdejong** 2018-09-19 07:04 UTC
