### ISSUE TITLE
extend existing math.js functions

### ISSUE THREAD

**Issue by spitzbubchen** [josdejong/mathjs#807] opened 2017-03-08 16:43 UTC
I would like to extend the mean() function to offer additional support:

```js
function mean() {
	console.log(arguments);
	values = [];
	$.each(arguments, function(index, item) {
		console.log(item, typeof item);
		if ($.isNumeric(item)) {
			values.push(item);
		}
	});
	if (values.length > 0) {
		console.log(values)
		return math.mean(values);
	} else {
		return NaN;
	}
}

// Import
math.import({
  mean: mean
});
```

However, doing this leads to the following error:

`Uncaught Error: Cannot import "mean": already exists`

**Comment by FSMaxB** [comment] 2017-03-08 18:40
You should import it like this:

```js
math.import({mean: mean}, {override: true});
```

See the [documentation](http://mathjs.org/docs/core/extension.html) about additional options.

**Comment by spitzbubchen** [comment] 2017-03-11 21:38
Now it does not give me the `Uncaught Error`, however, it  still does not seem to override the default mean function... I am using the most up to date mathjs version. This is what I have:

		function mean2() {
			var values = [];
			for (var i = 0; i < arguments.length; i++) {
				console.log(arguments[i]);
				var value = arguments[i];
				if (!isNaN(parseFloat(value)) && isFinite(value)) {
					values.push(value);
				}				
			}			
			console.log(arguments, values)			
			if (values.length > 0) {
				var total = 0;
				for(var i = 0; i < values.length; i++) {
					total += values[i];
				}
				var mean = total / values.length;				
				return mean;
			} else {
				return NaN;
			}
		}	
		
		// Import
		math.import(
			{ mean: mean2},
			{ override: true}
		);

**Comment by FSMaxB** [comment] 2017-03-12 10:43
Strange I cannot reproduce your problem, it seems to work with the latest mathjs from the master branch.

**Comment by josdejong** [comment] 2017-03-12 12:52
I think what's going on here is that the expression parser has a transform for the function `mean`, and this transform is not automatically deleted when overriding `mean`. So the overridden function `math.mean(...)` works fine, but not via the expression parser `math.eval('mean(...)')`.

This transform can be deleted like:
```js
delete math.expression.transform.mean
```

I think it makes sense to let the import function to delete any existing function transform when an imported function is overridden.

**Comment by spitzbubchen** [comment] 2017-03-12 15:08
Yup, now it works! Changed to the following:

```
		// Import
		delete math.expression.transform.mean
		math.import(
			{ mean: mean2},
			{ override: true}
		);
```

**Comment by josdejong** [comment] 2017-03-12 19:08
:+1: 

let's keep this topic open until math.js removes this transform itself.

**Comment by FSMaxB** [comment] 2017-03-12 19:22
So I guess this is a bug then!

**Comment by spitzbubchen** [comment] 2017-03-15 20:49
Ideally, I would like to use the built in mathjs mean() function, however, it seems only to calculate when all variable are defined in the scope.  I currently, have a form with several inputs and I would like to calculate the mean even if not all the inputs are filled. Wondering if you guys have a better idea than my current method of creating a custom mean() to filter out undefined scope variables.
```
$('#' + variable).unbind('change').change(function() {
	MATH.scope[variable] = parseFloat($('#' + variable).val());
	$.each(MATH.list[variable], function (index, item) {
		try {
			var value = math.eval(item.equation, MATH.scope);
			var input = $('#' + item.name);
			input.val(value);
		} catch(error) {
			console.log(error);
		}
	});			
});	
```

**Comment by josdejong** [comment] 2017-03-19 09:37
The underlying issue has been fixed in the develop branch, so from the firstnext version you will not have to delete existing transforms yourself anymore.

Regarding dealing with empty values in mean, there is an existing topic #353 so we can continue the discussion there.

**Closed** 2017-03-26 18:39 UTC
Labels: bug, question
