### ISSUE TITLE
priority of operators in math.parse()

### ISSUE THREAD

**Issue by meghna786** [josdejong/mathjs#3107] opened 2023-12-17 17:03 UTC
The issues section is used only for bug reports. Please use the [Discussions](https://github.com/josdejong/mathjs/discussions) section to ask questions and share ideas and suggestions.

**Describe the bug**
if I type math.parse('a*b/c')
then multiplication is done first

**To Reproduce**
I want it to divide first as according to DMAS, divide has more priority! Is there any way I can change priorities of operators for math.parse?

**Comment by josdejong** [comment] 2023-12-18 08:02
Duplicate of #3108, let's continue the discussion there.

**Closed by josdejong** 2023-12-18 08:02 UTC
Labels: duplicate
