### ISSUE TITLE
Precision attribute for rounding functions

### ISSUE THREAD

**Issue by ahallez** [josdejong/mathjs#1021] opened 2018-01-21 10:48 UTC
Hi,

Would it be an option to add a second optional argument to the rounding functions (round, floor, ceil) to indicate the precision of the rounding?

e.g. round(3.234, 2) would return 3.23

**Comment by FSMaxB** [comment] 2018-01-22 00:00
Mathjs already does exactly that! See [here](http://mathjs.org/docs/reference/functions/round.html) and [here](http://mathnotepad.com/#contents=N4IgzgLghhCmIC5RlgG1gYwgSwPYDtFRt8ATWAD0QEYAacaAJwkQAZ7Yy2BfesDRrlSoAKrgAOPDhXGNYYMHnxhEAbVAA3KKgCu8BCEE6yACgDMAOgBMZgCy0ABFYCUIegFtY0It16bteoggbiCe3ki%2BALr0GrCMigSIZvQ64qQwsKRBVqzUABwAtLkFVlYirKwIFQjUrBYAbLZmAFog3EA%3D)

**Comment by FSMaxB** [comment] 2018-01-22 00:01
Not for `floor` and `ceil` though.

**Comment by ahallez** [comment] 2018-01-22 09:56
Ok, I didn't check the documentation for round, because I'm mostly interested in floor and ceil.

**Comment by FSMaxB** [comment] 2018-01-22 11:17
@josdejong Do you think this should be implemented? I don't think it is 100% trivial, especially for all the different types.

@ahallez Do you know any other places where something like this has been implemented. e.g. Matlab, numpy etc.?

**Comment by ahallez** [comment] 2018-01-22 12:35
@FSMaxB it looks like the same pattern returns in most libraries. round has a precision argument and floor and ceil don't.

**Comment by Nekomajin42** [comment] 2018-01-22 13:21
@FSMaxB
Excel has this argument for roundup and rounddown.

**Comment by FSMaxB** [comment] 2018-01-22 13:49
I wonder, wouldn't the following be a workaround for ceil?

```js
round(number + sign(number) * 10^(-precision)*0.5, precision)
```

**Comment by Nekomajin42** [comment] 2018-01-22 19:56
@HarrySarson 
I agree, it's not a common case, however, as a teacher I've met problems, where this exact feature came handy in Excel. Let me show an example:

*You have a shop, and you want to give a 10% discount for certain items, but to make it consistent, you change the last digit to 9.*

Examples:

|Original|New|
|---|---|
|800|729|
|150|139|
|240|219|

The problem is that you have to add a different number to the last digits to make it 9. But it can be done by rounding the discount value down to the second digit, and add 9 is each case: `floor(original*0.9, -1) + 9`

This is how Excel works. (Although it has both `rounddown()` and `floor()`, and they work different.)

**Comment by josdejong** [comment] 2018-01-23 07:37
Though not a very common use case, I think it can be useful to have support for passing a number of digits to `floor` and `ceil` as optional second argument. I would like to add  `fix` to this list too though to have it complete. 

Thanks for sharing your use case Toth.

Fraction.js already has built in support for this. For number and BigNumber we'll have to implement this. We have to be careful not to introduce rounding-off issues when multiplying with 10^digits and then dividing again. That reminds me of a nice piece of work in PR #894 by @ericman314  that's still open, which addresses round-off errors in fix, ceil, and floor. I think we should finish that first, it could make implementing support for digits easier to implement.

**Comment by lwirtz** [comment] 2018-01-26 20:21
Yes @FSMaxB. One use case would be fee calculations based on percentages that would always round up to the nearest whole cent. I'm building a fee calculator for a government entity using your API through a bot to show customers what specific services will cost (they can't actually pay through the web, but this is a reoccurring request to easily calculate fees based on age and other selections). I would like to calculate the credit card fee (based off of a percentage) if they have selected that as their preferred payment method. If I can add the second argument for ceil, then the total will always be displayed in the appropriate format and at the proper amount.

Thanks!

**Comment by taoqf** [comment] 2018-01-31 08:59
I need this, too. my use case is simple, so i didn't commit a pr. 
```ts
export default function ceil(val: number, n = 0) {
	if (n > 0) {
		const factor = Math.pow(10, n);
		return Math.ceil(val * factor) / factor;
	} else {
		return Math.ceil(val);
	}
}
```

**Comment by lazybean** [comment] 2018-05-02 10:41
It would be nice to be able to pass negative precision, to round to nearest 10, 100 ,...
Math.round(118,-1)  // 120
Math.round(118, -2) // 100

**Comment by josdejong** [comment] 2018-05-05 07:47
Interesting idea @lazybean :)

**Comment by josdejong** [comment] 2022-09-02 15:05
This has been implemented already in the meantime, I will close this issue.

**Closed by josdejong** 2022-09-02 15:05 UTC
Labels: feature
