### ISSUE TITLE
Unsort eigenvalues

### ISSUE THREAD

**Issue by carllau999** [josdejong/mathjs#1929] opened 2020-07-29 19:29 UTC
Is it possible to unsort the eigenvalues when calling eigs(...).values?

**Comment by josdejong** [comment] 2020-07-30 12:31
There is no option to alter the sorting of the returned eigen values or vectors. Can you explain why you need this, what is you use case?

**Comment by carllau999** [comment] 2020-08-01 10:28
I have a graph, and I want to find the influence of each node, which is calculated by the eigenvectors from the adjacency matrix of the graph. But since it's unsorted I don't know which vector corresponds to which node... hope you can help!

**Comment by josdejong** [comment] 2020-08-02 10:53
The comments in the function `eigs` and the code suggest the results are sorted (see [eigs.js#L25](https://github.com/josdejong/mathjs/blob/develop/src/function/matrix/eigs.js#L25) and [eigs.js#L331-L355](https://github.com/josdejong/mathjs/blob/develop/src/function/matrix/eigs.js#L331-L355)). Are you sure the output is not sorted? If so, it may be a bug in the implementation.

**Comment by rnd-debug** [comment] 2020-08-02 18:05
To reproduce the issue:
```
let A = [[3,0],[0,2]]
console.log( math.eigs(A)) // { values: [ 2, 3 ], vectors: [ [ 0, 1 ], [ 1, 0 ] ] }
let B = [[2,0],[0,3]]
console.log( math.eigs(B)) // Expecting the same, but got : { values: [ 2, 3 ], vectors: [ [ 1, 0 ], [ 0, 1 ] ] }
```

**Comment by carllau999** [comment] 2020-08-10 07:39
The feature I'm hoping for is to unsort the values. As you mentioned eigs.js sorts the results, but this means I don't know which eigenvector corresponds to whichever node from the adjacency matrix

**Comment by josdejong** [comment] 2020-08-10 15:49
Ah of course, I get it. I guess it makes sense to extend the function `eigs` with an option `{ sorted: true | false }`

@arkajitmandal what do you think?

**Comment by arkajitmandal** [comment] 2020-08-10 16:38
I think the present implementation, it sorts the eigenvalues and accordingly gives out eigenvector, so its not that just the eigenvalues that are sorted. I am not sure if this "unsorted" option will serve any purpose since it will just mean randomizing the eigenvalues and eigenvectors. 

Let me know if 'eigs' is giving out any  troubles.

**Comment by josdejong** [comment] 2020-08-10 19:33
Thanks for your input. If there is no relation between the original matrix and the (unsorted) order of the eigenvalues, there is indeed no value in outputting unsorted results. Sorting them makes sense then, it normalizes the output.

So @carllau999 it looks like at least the current implementation of `eigs` doesn't support what you're looking for. I do not know if other algorithms do have this relation.

**Comment by arkajitmandal** [comment] 2020-08-11 01:49
@carllau999, if you are looking for ith eigenvector upon diagonalizing matrix H, that is the vector that corresponds to the eigenvalue math.eigs(H).values[i]  , it will be math.eigs(H).vectors[i]

**Comment by carllau999** [comment] 2020-08-17 20:46
@arkajitmandal  but is it possible to map each row in the adjacency matrix to an output eigenvalue?

**Comment by m93a** [comment] 2020-09-26 16:45
@carllau999 Matrices just don't work like that. Eigenvalues are a property of the whole matrix, not its individual rows. Changing one row can change all of the eigenvalues. Eigenvalues correspond to their respective eigenvectors, but there's no fundemental relation between rows of an matrix and its eigenvalues. For example, when you swap the i-th and j-th row (followed by equivalent column transformation), the eigenvalues stay exactly the same.

**Comment by josdejong** [comment] 2020-09-26 17:06
Thanks for your explanation Michal, I'll close this question now.

**Closed by josdejong** 2020-09-26 17:06 UTC
Labels: question
