### ISSUE TITLE
Issue with complex numbers

### ISSUE THREAD

**Issue by onkarjit** [josdejong/mathjs#893] opened 2017-07-06 08:41 UTC
`(-1) ^ (1 / 2)` returns `6.123233995736766e-17 + i` however isn't that supposed to return just 

`i`?

Also for example:

`(-25) ^ (1 / 2)` returns `3.061616997868383e-16 + 5i` but if I'm right it should return just `5i`?

**Comment by firepick1** [comment] 2017-07-06 14:00
I use mathjs for engineering. Library size performance are therefore primary concerns.  The tricky thing about addressing precision issues is that they might open up the temptation to address all such use cases with special code that slows down mathjs and makes it larger. I would therefore propose that we not fix this so that we can keep mathjs lean and fast. For example, if complex numbers have a base implementation that uses 64-bit doubles, then the above is perfectly acceptable.  On the other hand, if complex arbitrary precision numbers are important then that would be an issue for an optional extension to core mathjs.

**Comment by ThomasBrierley** [comment] 2017-07-06 15:02
It does feel like a slippery slope, round off error affects all floating point math. On the other hand the output can be particularly unhelpful in some practical cases. At least one of those cases is already being looked at in #868 by checking equality based on some epsilon (that approach would apply to most issues of this type).

Complex number have the same problem as trig functions in that they use Pi which is irrational, but there are sometimes ways around that without resorting to more fallible equality checks:

https://github.com/josdejong/mathjs/issues/755#issuecomment-263756291

Although this might be a lot harder for complex numbers as all operators would have to use some representation of i that is rational on boundaries... might not even be possible.

Personally I think these problems are better solved where they likely cause a problem (e.g when presented to a user), http://mathnotepad.com/ does this nicely, it reduces `(-1) ^ (1 / 2)` to i + "round off error"

**Comment by josdejong** [comment] 2017-07-07 08:02
Ideally we should be able to configure whether we want to use high precision BigNumbers in complex numbers or regular, fast numbers with more round-off errors when working with complex numbers, this is a feature I would love to see implemented, and is already on the wish list :)

See #823

**Comment by josdejong** [comment] 2022-08-26 13:41
Closing as a duplicate of #2709

**Closed by josdejong** 2022-08-26 13:41 UTC
