### ISSUE TITLE
(0+0i)^2 is NaN - aNi

### ISSUE THREAD

**Issue by Jutanium** [josdejong/mathjs#578] opened 2016-02-24 02:44 UTC
Am I missing something? Shouldn't (0+0i)^2 be 0? MathJS gives me NaN - aNi. (0+0i)(0+0i) is correctly evaluated as 0.

The same problem goes for (0+0i) to other powers.

**Comment by FSMaxB** [comment] 2016-02-24 09:00
I'm closing this because it's a duplicate of #564.

**Closed by FSMaxB** 2016-02-24 09:00 UTC
