### ISSUE TITLE
Imported function help

### ISSUE THREAD

**Issue by dvd101x** [josdejong/mathjs#2354] opened 2021-11-29 22:30 UTC
When using math.import and importing a function I would like for it to work with the help function

``` javascript
// define new functions and variables
math.import({
  myvalue: 42,
  hello: function (name) {
    /**
     * This function says hello
     *
     * Syntax:
     *
     *     math.hello("David")
     *     math.hello("Jos")
     *
     * Examples:
     *
     *     math.hello("David")               // returns "hello, David"
     *
     * See also:
     *
     *    compare, compareNatural
     *
     * @param {... *} args  A single string or a list of strings
     * @return {*} all strings
     */
    return 'hello, ' + name + '!'
  }
})
```

`help(hello)`

```
This function says hello

Syntax:

    math.hello("David")
    math.hello("Jos")

Examples:

    math.hello("David")               // returns "hello, David"

See also:

   compare, compareNatural
```

https://mathjs.org/docs/core/extension.html#extension

**Comment by josdejong** [comment] 2021-12-01 07:50
Hm that is a good question, there isn't really an API for that right now. 

I can think of two workarounds:

1. When using the ES6 library, you can add your docs to the globally exported `docs`

    ```js
    import { create, all, docs } from 'mathjs'
    const math = create(all)

    const myHelloDocs = {
      name: 'hello',
      category: '...',
      syntax: [
        '...'
      ],
      description: '....',
      examples: [
        '...'
      ],
      seealso: [
        '...'
      ]
    }
    
    // add custom docs to the globally exported docs
    docs.hello = myHelloDocs
    
    // now you can use help(hello)
    ```

2. Override the function `help` with your own version which first checks whether the input is `hello`, if so return `new Help(myHelloDocs)`, and otherwise call the original `help` function.

**Comment by dvd101x** [comment] 2021-12-14 16:02
Thank you, I will try both.

I'm working on an implementation of mathjs with some thermodynamics properties from the coolprop. It benefits greatly from the physical units of mathjs.

**Comment by josdejong** [comment] 2021-12-19 16:56
Thanks, good to hear 👍😄

**Comment by gwhitney** [comment] 2023-10-03 02:34
Closing as duplicate of #2047.

**Closed by gwhitney** 2023-10-03 02:34 UTC
Labels: feature, help wanted
