### ISSUE TITLE
Error TS1203: Export assignment cannot be used [for ESM]

### ISSUE THREAD

**Issue by nalply** [josdejong/mathjs#2983] opened 2023-06-26 10:23 UTC
**Error summary**
https://github.com/josdejong/mathjs/blob/develop/types/index.d.ts#L5 has an export assignment (`export = math`) but this seems not to be allowed for ECMAScript modules.

**To Reproduce**
Probably I am doing something shady, but I am trying to use mathjs for the browser without bundling. I symlinked `dist/math.js` to `m.js` and `types/index.d.ts` to `m.d.ts` in my `ts` source directory. I tried many other things to avoid bundling during development but kept failing, and I thought, perhaps I use the pre-bundled `dist/math.js` instead, but this also fails already when compiling TS.

I am willing to edit `types/index.d.ts` to fix this problem but need to understand a little better how mathjs is structured. For example, why export assignment? And how is `MathJsStatic` related to the default export `math`?

**Comment by josdejong** [comment] 2023-06-26 10:26
Thanks for your input Danial. I think this is a duplicate of #2919, please continue the discussion there.

**Closed by josdejong** 2023-06-26 10:26 UTC
