### ISSUE TITLE
math.eval and division of units

### ISSUE THREAD

**Issue by mannyd28** [josdejong/mathjs#887] opened 2017-06-27 03:16 UTC
It appears to me that math.eval is not identifying the correct unit of the quotient when the dividend and divisor both have (the same or different) units:

```javascript
>math.eval('4m / 1s');
//expected: 4 m / s
//actual: 4 m s

>math.eval('4m / 1m');
//expected: 4 m
//actual: 4 m^2

>math.eval('A=4m; B=1m; A/B');
//expected: [4m]
//actual: [4]
```

**Comment by josdejong** [comment] 2017-06-27 19:31
This can indeed be confusing behavior. The reason is that implicit multiplication has the same precedence as division, so `4m / 1s` is evaluated as `4 * m / 1 * s = ((4 * m) / 1) * s = 4 * m * s`. We may want to change this behavior but this is still an open discussion.

As for your second case, the expected value is `4`, and your third case is just correct (meter divided by meter is unit less).

This is a duplicate of #792, let's continue any discussion there ok?

**Closed** 2017-06-27 20:14 UTC
Labels: duplicate
