### ISSUE TITLE
Recusively parse and evaluate expressions

### ISSUE THREAD

**Issue by rmickus** [josdejong/mathjs#1673] opened 2019-11-13 19:33 UTC
I have an application where certain equations rely on other equations. The ordering of the dependencies of equations is not known at run time. So I would like to be able to use a scope to recursively evaluate each expression without throwing errors. Right now I can't seem to figure this out and was curious if this feature is possible.

For example, If I have in my scope:

`let scope = {
    a: "4 + 3",
    b: "a + 3"
}`

And I want to evaluate the value of b like:

`math.parse("b").compile().evaluate(scope)`

I expect to see the value 10, but instead I get:

`a + 3`

Okay, not a huge deal. I can just run a while loop that stops when I see a number. But If I evaluate 'a + 3' in the same manor, I get the following error:

> Uncaught Error: Cannot convert "4 + 3" to a number

So again, to reiterate my question, is it possible to recursively evaluate expressions within the MathJS library? If so, please point out my mistake, and if not, perhaps this might be a feature to consider?

**Comment by josdejong** [comment] 2019-11-13 20:05
Yes, that is an interesting case, that's more or less what Excel does for example.

This is a duplicate of the discussion in #791, which is still open. Shall we continue the discussion there to keep it focused?

**Closed** 2019-11-16 14:33 UTC
Labels: duplicate
