### ISSUE TITLE
improve bigFactorial algorithm

### ISSUE THREAD

**Issue by kmdrGroch** [josdejong/mathjs#1687] opened 2019-12-07 04:28 UTC
You can use different algorithms of factorial to speed this 2-8 times. Universal one (twice as fast):
[i am using bigint's in implementation, but logic is the same]
```js
function factorial(n) {
  if(n === 0n || n === 1n) {
    return 1n;
  }
  if(n % 2n === 1n) {
    return n * factorial(n - 1n);
  }

  let p = n;
  let prod = n;

  while(p > 2n) {
    p -= 2n;
    n += p;

    prod *= n;
  }

  return prod;
}
```

If you are interested in the less universal (faster than this after n=1400), I could provide it in comment

**Comment by josdejong** [comment] 2019-12-09 18:55
Performance improvements are of course always welcome Bartosz :) Would you like to work this out in a Pull request, or can we ask the community to pick this up?

I think it will be useful to write a little benchmark to make sure we're actually improving (see `/benchmark` folder.

**Comment by kmdrGroch** [comment] 2019-12-09 20:30
@josdejong for now, I have benchmarks for my implementation. This algorithm is written to be fast tho. Should be always ~2 times faster since you have twice less numbers
20! = 1 * 2 * 3 * 4 * ... * 20  ( 20 terms )
20! = 20 * (20 + 18) * (20 + 18 + 16) * (20 + ... + 2)  (9 terms or so)

**Comment by kmdrGroch** [comment] 2019-12-09 20:36
@josdejong I have one question tho. Should I use this math library or can I use BigInt?

**Comment by kmdrGroch** [comment] 2019-12-09 21:43
![image](https://user-images.githubusercontent.com/28489774/70475615-cfca1780-1acc-11ea-854a-575efdb10adf.png)
After a small test, it seems it is faster (from 8! tho, but we can hardcode first 7 factorials I guess)

**Comment by kmdrGroch** [comment] 2019-12-11 00:29
@josdejong would you also like a proof paper for this algorithm?

**Comment by kmdrGroch** [comment] 2019-12-11 03:19
Update: I have been working theoretically investigating this subject, and I have managed to make this algorithm twice as fast, these are results on this moment (right now I have implemented square difference factorial, as you can see in PR, although I am planning to check other possibilities too)

```
calculating speed for factorial 10        
factorial by definition: 0.088ms
square difference factorial: 0.045ms      
doubleFactorial square difference: 0.082ms
recursive binary factorial: 0.112ms       

calculating speed for factorial 100       
factorial by definition: 0.025ms
square difference factorial: 0.024ms      
doubleFactorial square difference: 0.026ms
recursive binary factorial: 0.052ms       

calculating speed for factorial 1000      
factorial by definition: 1.438ms
square difference factorial: 0.357ms      
doubleFactorial square difference: 0.231ms
recursive binary factorial: 0.626ms       

calculating speed for factorial 10000     
factorial by definition: 73.748ms
square difference factorial: 38.261ms
doubleFactorial square difference: 17.682ms
recursive binary factorial: 11.47ms   

calculating speed for factorial 100000
factorial by definition: 10.981s
square difference factorial: 5.647s
doubleFactorial square difference: 2.272s
recursive binary factorial: 997.771ms
```
(It has been written using BigInt, not this library, so probably due to complexity I'll have to leave it as it is in PR right now)

**Comment by josdejong** [comment] 2019-12-15 08:45
Thanks

**Comment by josdejong** [comment] 2019-12-15 08:51
Thanks Bartosz, this benchmark clearly shows a factor 2 improvement, that's impressive :). I've merged the benchmark in the `develop` branch and fixed some linting errors that it complained about.

Anyone interested in replacing the current bignumber implementation with the faster one proposed here?

**Comment by kmdrGroch** [comment] 2019-12-15 13:30
I am still working theoretically on that. Give me a week or two, I'll try to handle this PR or at least write benchmarks :)
Also, I need to check edge cases like n = 0 or n = 1 since in my proof I am omitting it. I need to consult my maths teacher so he can check my proofs :)

**Comment by josdejong** [comment] 2019-12-15 20:53
> And @josdejong this version written in Benchmark is actually working one (it's not in BigInt)

Yes so it should be quite straight forward to replace the implementation with the one in from benchmark :)

I'll await your further experimentation.

**Comment by kmdrGroch** [comment] 2019-12-15 21:10
Exactly. It will probably be just copy-paste implementation :)

**Comment by kmdrGroch** [comment] 2019-12-17 16:30
@josdejong If you like, I have also quite fast algorithm for double factorial (the same logic as for factorial, so double speed).

**Comment by josdejong** [comment] 2019-12-21 12:45
That sounds interesting of course :)

**Comment by kmdrGroch** [comment] 2019-12-21 12:56
If you are interested, I have created a math library based in bigints. You might want to take a look on some implementations :)

**Comment by kmdrGroch** [comment] 2019-12-22 00:55
![download (1)](https://user-images.githubusercontent.com/28489774/71315442-8925d700-2455-11ea-9c5e-5fd6931e8667.png)

I was thinking of making a simple graph to illustrate speed of algorithms and came up with something like this (it is a rough version for simple illustrations)

**Comment by josdejong** [comment] 2019-12-23 09:29
That's nice, that really gives a clear insight on _how much_ performance improvement the different  give, and how good they score on different ranges of values. It's interesting to see that up to about `1450` the `initializeFactorial` has worse performance than the others. So if the typical use case is below that, it may yield a regression in real world applications. Do you have an idea on what range of values people normally need?

**Comment by kmdrGroch** [comment] 2019-12-23 14:10
Honestly, I have not done research in this field. For now, I am only testing different algorithms since I'm super interested in the "speed" part, not the "usage"/"social" part.

Although the speed is worse for numbers 1450 < , I still find this algorithm usable. You just need to "swap" algorithms for different thresholds:
```
n < 8 -> just return value
8 <= n < 1450 -> factorial3
n >= 1450 -> initializeFactorial
```
using this method, we always get the best performance possible

**Comment by josdejong** [comment] 2019-12-24 21:03
Yeah I can imagine that it's really interesting to see how all these different approaches compare :) I'm sure it will also differ a lot whether working with numbers, BigNumbers, BigInt, etc.

I think it makes sense to put all your different algorithms and benchmarks and research in a separate repository (and maybe an npm library) purely focused on the best performance of factorial for large values. It goes a bit too far though for mathjs, where we try to balance usability, performance, code complexity and maintainability, and bundle size.

I would love to have the improvements that are currently in [/test/benchmark/factorial.js](https://github.com/josdejong/mathjs/blob/develop/test/benchmark/factorial.js) integrated in the factorial function of mathjs, but let's not go for #1691 at this point, see my reasoning in https://github.com/josdejong/mathjs/pull/1691#issuecomment-568411408. Is that ok with you?

**Comment by kmdrGroch** [comment] 2019-12-24 23:16
I'll remove `initializeFactorial` algorithm due to high complexity of it. Instead I'll try benchmarking my other model (factorial3) which uses the fact that: `n!` can be *almost* written as `n!! * 2 ** (n/2) * (n/2)!. It is has super easy proof by itself and both double factorial and factorial uses quite similar algorithm, so it is easy to understand. Full implementation in BigInt:
```js
function doubleFactorial(n) {
  switch((n + 1n) % 4n) {
    case 0n:
      const p = (n - 1n) / 2n;
      n += 1n;
      let prod = 1n;
  
      for(let k = 1n; k <= p; k += 2n) {
        prod *= (n - k) * k;
      }
    
      return prod;
    case 2n:
      return n * doubleFactorial(n - 2n);
  }

  return 2n ** (n / 2n) * factorial3(n / 2n);
}

function factorial3(n) {
  if(n < 7n) {
    return [1n, 1n, 2n, 6n, 24n, 120n, 720n][+`${n}`]
  }

  if(n % 2n === 0n) {
    const k = n / 2n;
    return 2n ** k * doubleFactorial(n - 1n) * factorial3(k);
  }

  return factorial3(n - 1n) * n;
}
```

**Comment by josdejong** [comment] 2019-12-25 11:16
These are very well understandable algorithms! Looks good. 

Practical questions: 

1. mathjs does not have any support for BigInt. It makes sense to me to add BigInt support for mathjs but that only works it we add support for at least all arithmetic functions for example and add documentation etc, that requires some work. I think that's too big to be part of this PR though.
2. The current implementation of `factorial` supports `number` and `BigNumber`. Can your algorithms be transformed for `number` and `BigNumber` instead of `BigInt? Are they then faster than the current implementations?
3. If I understand it correctly, the faster implementations that you propose above works only for integer numbers? And since it's using BigInt, it will not work on all browsers. I think it is essential to have a `factorial` implementation which works on all browsers and supports floating point. So should we create a switch in the current implementations for `number` and `BigNumber` to use this fast integer implementation when the input is an integer value, and otherwise use an other implementation?

**Comment by kmdrGroch** [comment] 2019-12-25 12:26
There is no problem in changing it from bigint to bignumber, the only drawback is performance, which I'll measure to ensure its indeed faster.

If it comes to other functions, if needed, you could consider using parts of my library which basically works quite similar to BigNumber, but on BigInts.

But I am probably able to write every function using BigNumbers. Still I have to measure performance though :/

**Comment by josdejong** [comment] 2019-12-26 20:04
Let's focus on improving factorial (number and BigNumber) for now and keep BigInt support separate ok? I'm looking forward to see what you come up with :)

**Comment by kmdrGroch** [comment] 2019-12-27 13:56
@josdejong I have removed that complex algorithm and was playing with another algorithm, but I couldn't make it fast enough (even with BigInt, since I had to use `BigInt(n)` instead of 1n,2n etc which make it slow). So for now the fastest algorithm available is already on. Even after optimisations, the difference was insignificant, so this is the fastest available for now :/ (still double speed is good i guess)

**Comment by josdejong** [comment] 2019-12-28 15:51
Double speed is awesome :sunglasses: :rocket: ! Bummer that the other optimizations didn't work out, but very good to have this verified with some benchmarks! Thanks for all your effort. 

I think we can close #1691 then, and the next step would be to actually implement the 2x improvements that are already in `test/benchmark/factorial.js`?

**Comment by kmdrGroch** [comment] 2019-12-28 17:16
Well yeah. I guess it's enough to just copy /paste implementation to SRC folder :) I can do it tomorrow /maybe today

**Comment by josdejong** [comment] 2019-12-31 10:33
Thanks Bartosz, I've merged your PR now! It's a very nice improvement and I love it that it's achieved by just a few lines of code.

**Comment by josdejong** [comment] 2019-12-31 10:56
Improved `factorial` is now available in `v6.3.0`

**Closed by josdejong** 2019-12-31 10:56 UTC
Labels: feature, help wanted

**Comment by kmdrGroch** [comment] 2019-12-31 13:13
If you have any algorithm you want to be improved, message me. I'll take a look then ;p

**Comment by josdejong** [comment] 2019-12-31 14:28
Thanks! It would be great if you could have a look at the performance of `det` some day. This is currently like 100 times slower than we would expect, see #908.

**Comment by kmdrGroch** [comment] 2020-01-29 17:09
@josdejong If you are interested, we could change the factorial algorithm again in the future. It is quite fast and implementation isn't that hard to understand:
```js
function Factorial(n) {
  if (n < 2n) {
    return 1n;
  }

  let p = 1n;
  let r = 1n;
  let nn = 1n;

  let h = 0n, shift = 0n, high = 1n;
  let log2N = BigInt(Math.floor(Math.log2(+`${n}`)));

  function Product(n) {
    const m = n / 2n;
    if (m === 0n) {
      return nn += 2n;
    }
  
    if (n === 2n) {
      return (nn += 2n) * (nn += 2n);
    }
  
    return Product(m) * Product(m);
  }

  while (h !== n) {
    shift += h;
    h = n >> log2N--;
    var len = high;
    high = (h - 1n) | 1n;
    len = (high - len) / 2n;

    if (len > 0n) {
      p *= Product(len);
      r *= p;
    }
  }

  return r << shift;
}
```

**Comment by kmdrGroch** [comment] 2020-01-29 17:11
![download](https://user-images.githubusercontent.com/28489774/73379522-b2dae500-42c2-11ea-8e94-a04ba60cfc3a.png)

Difference between this one (FactorialSplit) and current implementation [note that these are implemented using BigInt not BigNumber so the results my differ a little]

**Comment by josdejong** [comment] 2020-02-01 09:19
> If you are interested, we could change the factorial algorithm again in the future. It is quite fast and implementation isn't that hard to understand

Yes of course :) That algorithm looks very simple!

We should be careful not to compare apples with pears though: so far mathjs has no built in support for BigInt. It would be great to add this but I think it only makes sense if we create support for it for all basic arithmetic functions (add, subtract, etc), we discussed that before I think. 

I understand your implementation only works for BigInt. Can it be used for `number` too? 

I was thinking, we could make a switch in the current number and BigNumber implementation: if the input is integer and the browser has BigInt support, switch to this fast algorithm you propose above. This way BigInt is only used under the hood. What do you think?

**Comment by kmdrGroch** [comment] 2020-02-01 09:59
Most of this algorithm can use normal numbers. I am using BigInt everywhere since conversion number -> BigInt is slow. There is no problem for me for changing your implementations, but keep in mind, that BigInt isn't supported everywhere. If you take a look at my BigMath library, I have written there which browsers /node versions are supported

**Comment by josdejong** [comment] 2020-02-01 10:26
If we do start using `BigInt` under the hood we definitely have to create a check on whether `BigInt` is supported in the first place.

**Comment by kmdrGroch** [comment] 2020-02-01 11:17
@josdejong the problem is that `BigInt(5)` is slow, and `5n` will throw an error if a browser doesn't support BigInt :/ well... I'll see what can be done

**Comment by josdejong** [comment] 2020-02-01 11:33
You can probably create some constants for that like `const five = BigInt(5)`.

**Comment by kmdrGroch** [comment] 2020-02-01 11:41
Indeed. Well. We will see later. For now, I have exams at university and my own projects so I don't have that much time. But I'll inform you when I find some nice algorithm ;D

**Comment by josdejong** [comment] 2020-02-01 11:42
👍 good luck with your exams
