### ISSUE TITLE
MathJS fromTex() function possible?

### ISSUE THREAD

**Issue by drparham** [josdejong/mathjs#566] opened 2016-02-10 22:58 UTC
I'm wanting a way of converting a LaTeX string back to a string that math.js can evaluate. 

Is this possible in Math.js?

**Comment by FSMaxB** [comment] 2016-02-10 23:48
This is not possible at the moment and probably out of the scope of the library (@josdejong: Do you agree?). For this to work, we would need a new parser (or something based on an existing LaTeX parser) and be able to somehow parse this into a tree of MathJS nodes. This would certainly be technically possible on a small subset of TeX/LaTeX, but then there's the question where to draw the line (note that `1 + 1` is a subset of TeX, and MathJS can parse that).

I could still be proven wrong, but I guess it's unlikely that this feature will be implemented in the near future, if at all.

**Comment by drparham** [comment] 2016-02-11 00:20
I've been unable to find anything that parses LaTex/Tex into something that can be evaluated. Basically need the opposite function of toTex().

**Comment by josdejong** [comment] 2016-02-11 08:58
This is a duplicate of #308.

I think @drparham is right in that there is no solution for parsing and evaluating latex. Or maybe mathjax can convert from latex to asciimath? Having a solution for this in general would be powerful, though it will be a lot of work. Just thinking aloud: maybe it's best to develop such a parser as a standalone library from and then integrate it in math.js.

**Comment by pkra** [comment] 2016-02-11 11:49
> Or maybe mathjax can convert from latex to asciimath? 

We don't have that. (La)TeX is generally too powerful and our TeX-like input is also extensible through arbitrary code (instead of other grammar-based approaches) so converting to asciimath seems difficult. (Though perhaps a naive approach might already help, I wouldn't know.)

What we do have is a new tool that generates semantic information from MathML (which is what MathJax converts everything into internally) which is used for smarter layout and accessibility (voicing, navigation).  The "semantic tree" that's behind it might be usable to generate something for math.js. cc @zorkow who leads that work.

**Comment by josdejong** [comment] 2016-02-11 18:41
Hi @pkra, good to hear from you :) Such a semantic tree is indeed what we would need, and if we could parse LaTeX into MathML and generate a tree that way, we're already close :) Worth a shot...

**Comment by drparham** [comment] 2016-02-11 19:05
Sounds promising. I am trying to figure out how to create a semantic tree for latex to properly break up LaTeX equations, and that part seems to be the most difficult. Breaking the strings up, or doing regex for specific latex formatting is easy, but you quickly run into the problem of rebuilding the equation properly.

**Comment by josdejong** [comment] 2016-02-12 07:43
> I am trying to figure out how to create a semantic tree for latex to properly break up LaTeX equations

are you looking into MathJax for this, since MathJax already does this (see https://github.com/josdejong/mathjs/issues/566#issuecomment-182824835)?

**Comment by zorkow** [comment] 2016-02-12 09:16
We could expose the semantic tree before it is embedded into data attributes in the MathML expression. 

I do have a yet unfinished algorithm to re-construct the semantic tree from the data attributes. It is not straight forward, as some semantic elements are shortened during the embedding, and need to be reconstructed.

But for your purposes it might be preferable to straight from LaTeX to semantic tree anyway.

**Comment by josdejong** [comment] 2016-02-12 13:15
That sounds good @zorkow . Ideal would be indeed to get a semantic tree directly from LaTeX. Next step would be to convert this in an [expression tree](http://mathjs.org/docs/expressions/expression_trees.html) for math.js, or into a an expression (string) that can be parsed by math.js again (syntax is close to ASCII math but not 100%).

**Comment by zorkow** [comment] 2016-02-12 18:15
Our semantic tree is a term tree not unlike your expression tree. Maybe a bit more complex. Here is roughly what the quadratic formula looks like (copied from a PDF, sorry):

      =
x             /
     ±                   ·
  -        sqrt     2     a
  b           -
         b              · 
      b     2      4   a    c

**Comment by zorkow** [comment] 2016-02-12 18:16
Well that looked much better before I sent it off in ASCII! Sorry about that. I'll try it again.

**Comment by zorkow** [comment] 2016-02-12 18:18
http://www.cs.bham.ac.uk/~vxs/publications/2014/Sorge14.pdf
Last page, top of the left column.

**Comment by pkra** [comment] 2016-02-12 18:20
@zorkow wrap the ascii art in \`\`\` (before and after.)

**Comment by drparham** [comment] 2016-02-12 19:15
Would it be possible to grab the XML that gets sent to ChromeVox into  xml2json (https://bitbucket.org/surenrao/xml2json)  library and then parse the json into a JavaScript object? That might be the easiest solution. Once it's in object form, we should have the hierarchy to build an actual ASCII equation.

Thoughts?

**Comment by josdejong** [comment] 2016-02-13 11:27
@zorkow I took the liberty to replace your ASCII tree with a screenshot to keep the discussion clear.

This tree looks very similar to how the expression parser of math.js, or am I missing something? Of course not everything is supported by math.js (like `±`).

To give you an idea on the tree generated by math.js for the quadratic formula:

```js
math.parse('x= (-b + sqrt(b^2 - 4*a*c)) / (2*a)')
```

See this jsbin: http://jsbin.com/hacaxa/edit?html,output (developer console gives best overview)

**Comment by zorkow** [comment] 2016-02-13 19:21
@josdejong Thanks for taking the time for the screen shot.
Indeed the trees are quite similar. Main differences are that I collate operators. Also fences, if given, are treated explicitly. I would also assume that the representations will diverge more for complex structures like integrals, sums, table constructs. I do not know your syntax for those, so could not play with them.

@drparham  The [SRE](https://github.com/zorkow/speech-rule-engine) is now independent of ChromeVox anyway and can be used directly in node, cli or browser. That's how we connected it to MathJax. 
What currently happens is that MathJax sends the mml expression to the SRE which returns an enriched mml expression, that is, the internal semantic tree is folded into the MathML via data attributes. 
At this point it would not be a problem to return either the XML for the semantic tree or a json linearisation. I could probably brew something up next week. I wanted to expose the semantic enrichment via a node API anyway and we could add an option to MathJax-node to use that.

**Comment by drparham** [comment] 2016-02-15 15:44
@zorkow  That would be excellent!

**Comment by physikerwelt** [comment] 2016-02-23 11:57
:+1:

**Comment by trevorhanus** [comment] 2016-03-12 02:13
Has anyone worked on this lately? I'm interested in a fromTex() solution as well.

Would it be possible to parse a Tex string into an expression string that could be passed into MathJS? This seems quite possible to me, but I only just started looking into MathJS and Tex. 

Am I missing something?

eg: 
```
tex = "\frac{\sqrt{3 + 6}}{3}"
expr = fromTex(tex) 
expr => "(sqrt(3 + 6)) / 3"

math.eval(expr) => 1
```

**Comment by josdejong** [comment] 2016-03-12 11:24
It's on the wishlist but no one is actively working on it as far as I know.

**Comment by zorkow** [comment] 2016-03-12 17:15
@drparham I've by now exposed the semantic tree via the sre api. If you want to translate a LaTeX expression you have to go through MathJax-node. I created a new script tex2stree which makes that easy. It's not yet available via npm but in the develop branch of https://github.com/mathjax/MathJax-node

There's also a (quick and dirty) visualisation of the semantic tree at 
http://zorkow.github.io/semantic-tree-visualiser/visualise.html
or
https://github.com/zorkow/semantic-tree-visualiser
respectively, which uses the json as input.

**Comment by kisonecat** [comment] 2018-03-16 15:56
There is a fromLatex parser in https://github.com/kisonecat/math-expressions which @dqnykamp and I are working to improve (and connect with MathJS).

**Comment by josdejong** [comment] 2018-03-17 12:25
Cool @kisonecat ! Thanks for sharing. Will be interesting to see if/how we can connect this to mathjs

**Comment by harrysarson** [comment] 2018-09-14 10:33
As #308 is open and a duplicate I might close this in favour of the other issue.

**Closed by harrysarson** 2018-09-14 10:33 UTC
Labels: duplicate, question

**Comment by akashpradhan62539** [comment] 2024-02-16 08:59
I need math expression to latex code converter any one help me

**Comment by josdejong** [comment] 2024-02-16 09:24
mathjs expression to latex is available: 

```js
mathjs.parse('sqrt(pi / 2)').toTex()
```

**Comment by Ansh-Arora-0512** [comment] 2025-02-07 14:39
I know I'm very late to the discussion but I'm working on a project that involves converting user input in latex (using mathquill for an editable latex field) to an expression tree which I need to further manipulate. I'm using mathjs's expression trees and was worried the code I wrote to convert latex to expression trees already exists as a fromTex function. 

It doesn't, but that means I can contribute here by providing my code, which can convert latex expressions (excluding specialised notation for things matrices and sets) to expression trees:
[](https://github.com/Ansh-Arora-0512/diff-eq-visualiser)

The code makes use of a regex tokeniser and a modified version of the shunting yard algorithm, meaning it can be modified for your application pretty easily.

**Comment by josdejong** [comment] 2025-02-20 12:50
👍 thanks for sharing Ansh!
