### ISSUE TITLE
Error on Fraction.js dependency

### ISSUE THREAD

**Issue by cleversonmv** [josdejong/mathjs#3022] opened 2023-08-30 18:53 UTC
error on start:

Uncaught TypeError: Cannot set properties of undefined (setting 'type')
    at push../node_modules/mathjs/lib/esm/type/fraction/Fraction.js.Object.isClass (Fraction.js:9:1)
    at assertAndCreate (factory.js:35:1)
    at ./node_modules/mathjs/lib/esm/entry/pureFunctionsAny.generated.js (pureFunctionsAny.generated.js:62:1)

**Comment by danny237** [comment] 2023-08-30 19:06
Same here.

**Comment by josdejong** [comment] 2023-08-30 19:21
There is probably something breaking introduced in the latest version of Fraction.js, `fraction.js@4.3.1`, which was released less than 1 day ago.

https://www.npmjs.com/package/fraction.js?activeTab=versions

To work around it you can probably explicitly install `fraction.js@4.3.0` (not tested).

**Comment by cleversonmv** [comment] 2023-08-30 19:23
> There is probably something breaking introduced in the latest version of Fraction.js, `fraction.js@4.3.1`, which was released less than 1 day ago.
> 
> https://www.npmjs.com/package/fraction.js?activeTab=versions
> 
> To work around it you can probably explicitly install `fraction.js@4.3.0` (not tested).

not work too

**Comment by ai-rohit** [comment] 2023-08-30 19:31
> > There is probably something breaking introduced in the latest version of Fraction.js, `fraction.js@4.3.1`, which was released less than 1 day ago.
> > https://www.npmjs.com/package/fraction.js?activeTab=versions
> > To work around it you can probably explicitly install `fraction.js@4.3.0` (not tested).
> 
> not work too , I tested several versions and it didn't work

I downgraded the mathjs version which worked for me.

**Comment by infusion** [comment] 2023-08-30 19:34
Hi, v4.3.0 was not supposed to have breaking changes. I'm looking into what the problem is, I changed the import/require behavior only slightly and tested it. But I somehow missed something

**Comment by josdejong** [comment] 2023-08-30 19:36
I'm not yet able to reproduce an issue with `fraction.js@4.3.1`, not sure yet what is going on.

**Comment by cleversonmv** [comment] 2023-08-30 19:38
> > > There is probably something breaking introduced in the latest version of Fraction.js, `fraction.js@4.3.1`, which was released less than 1 day ago.
> > > https://www.npmjs.com/package/fraction.js?activeTab=versions
> > > To work around it you can probably explicitly install `fraction.js@4.3.0` (not tested).
> > 
> > 
> > not work too , I tested several versions and it didn't work
> 
> I downgraded the mathjs version which worked for me.

Which version?

**Comment by cleversonmv** [comment] 2023-08-30 19:40
i tried with all verisons:
 [4.3.1][4.3.0][4.2.1][4.2.0][4.1.3][4.1.2][4.1.1][4.1.0]

**Comment by infusion** [comment] 2023-08-30 19:42
The change occurred in 4.3.0, I then had to fix a minor thing that resulted in 4.3.1. Anyway, what is your environment? What is your node version? I downgraded even to node 16 and it works just fine for me.

**Comment by josdejong** [comment] 2023-08-30 19:50
It may help to throw away your `package-lock.json` and `node_modules` folder and do a fresh install.

**Comment by infusion** [comment] 2023-08-30 19:56
I reverted the change. Hope that helps with 4.3.2

**Comment by infusion** [comment] 2023-08-30 19:56
I have to dig a little deeper into what's going on here. But the package-lock could definitely be a problem!

**Comment by ai-rohit** [comment] 2023-08-30 20:03
> > > > There is probably something breaking introduced in the latest version of Fraction.js, `fraction.js@4.3.1`, which was released less than 1 day ago.
> > > > https://www.npmjs.com/package/fraction.js?activeTab=versions
> > > > To work around it you can probably explicitly install `fraction.js@4.3.0` (not tested).
> > > 
> > > 
> > > not work too , I tested several versions and it didn't work
> > 
> > 
> > I downgraded the mathjs version which worked for me.
> 
> Which version?

We were using 6.2.5 previously. So went back to it from v9.*.*. I tried downgrading to 7.0.0 and 8.0.0 but didnt work in both.

**Comment by infusion** [comment] 2023-08-30 20:04
is it now working again?

**Comment by ai-rohit** [comment] 2023-08-30 20:20
"mathjs": "^9.4.4",
"fraction.js": "4.2.0"

Node version: 18.16.0

Deleted node_modules and yarn.lock and did install again. Still getting the error.

Uncaught TypeError: Cannot set properties of undefined (setting 'type')
    at push../node_modules/mathjs/lib/esm/type/fraction/Fraction.js.Object.isClass (Fraction.js:9:1)
    at assertAndCreate (factory.js:35:1)
    at ./node_modules/mathjs/lib/esm/entry/pureFunctionsAny.generated.js (pureFunctionsAny.generated.js:63:1)
    at __webpack_require__ (bootstrap:853:1)
    at fn (bootstrap:150:1)
    at ./node_modules/mathjs/lib/esm/entry/mainAny.js (mainAny.js:1:1)

**Comment by ai-rohit** [comment] 2023-08-30 20:20
"mathjs": "^9.4.4",
"fraction.js": "4.2.0"

Node version: 18.16.0

deleted node_modules and yarn.lock and did install again. Still getting the error.

Uncaught TypeError: Cannot set properties of undefined (setting 'type')
    at push../node_modules/mathjs/lib/esm/type/fraction/Fraction.js.Object.isClass (Fraction.js:9:1)
    at assertAndCreate (factory.js:35:1)
    at ./node_modules/mathjs/lib/esm/entry/pureFunctionsAny.generated.js (pureFunctionsAny.generated.js:63:1)
    at __webpack_require__ (bootstrap:853:1)
    at fn (bootstrap:150:1)
    at ./node_modules/mathjs/lib/esm/entry/mainAny.js (mainAny.js:1:1)

**Comment by infusion** [comment] 2023-08-30 20:23
Even with fraction 4.2.0? This version is quite dated and had no problems. I introduced this problem probably yesterday with my ESM module change.

**Comment by ai-rohit** [comment] 2023-08-30 20:24
However when I bump mathjs version to the latest one.  I get the following error.

Fraction.js:9 Uncaught TypeError: Object.defineProperty called on non-object
    at Function.defineProperty (<anonymous>)
    at push../node_modules/mathjs/lib/esm/type/fraction/Fraction.js.Object.isClass (Fraction.js:9:1)
    at assertAndCreate (factory.js:35:1)
    at ./node_modules/mathjs/lib/esm/entry/pureFunctionsAny.generated.js (pureFunctionsAny.generated.js:22:1)
    at __webpack_require__ (bootstrap:853:1)
    at fn (bootstrap:150:1)
    at ./node_modules/mathjs/lib/esm/entry/mainAny.js (mainAny.js:1:1)

**Comment by infusion** [comment] 2023-08-30 20:26
even with a fresh install?

**Comment by ai-rohit** [comment] 2023-08-30 20:36
> even with a fresh install?

Yes. deleted node_modules, yarn.lock then installed.

**Comment by YuXueBJ** [comment] 2023-08-31 03:16
![image](https://github.com/josdejong/mathjs/assets/5047984/bbd55587-185b-4ffb-90ac-ef0388b79047)
I have the same problem

**Comment by Nagrom33** [comment] 2023-08-31 07:04
Struggle with the same problem i'm using node v 16.3

I have saved an old node_modules folder when i use this folder it runs good looked the versions i used there:
```
  "name": "mathjs",
  "version": "9.5.2",
  
      "fraction.js": "^4.1.1",
```

But when I change those in my package.json and remove package-lock.json, node_modules, and removed npm cache --force

Then run npm install, and getting the same error:
```
TypeError: fraction_js__WEBPACK_IMPORTED_MODULE_0__.prototype is undefined
    createFractionClass Fraction.js:9
    assertAndCreate factory.js:35
    js pureFunctionsAny.generated.js:62
    factory react refresh:6
    Webpack 31
lockdown-install.js:1:103865
    functors moz-extension://005fd067-6eb1-4869-9edd-f11ce4c7ac9a/lockdown-install.js:1
    (Async: EventListener.handleEvent)
    functors moz-extension://005fd067-6eb1-4869-9edd-f11ce4c7ac9a/lockdown-install.js:1
    repairIntrinsics moz-extension://005fd067-6eb1-4869-9edd-f11ce4c7ac9a/lockdown-install.js:1
    functors moz-extension://005fd067-6eb1-4869-9edd-f11ce4c7ac9a/lockdown-install.js:1
    <anonymous> moz-extension://005fd067-6eb1-4869-9edd-f11ce4c7ac9a/lockdown-run.js:4
    ```

**Comment by josdejong** [comment] 2023-08-31 07:31
Thanks Robert.

I'm just publishing a new version of mathjs that locks `fraction.js@4.2.0`, I hope that will temporarily solve this issue.

I still have to figure out how to reproduce this issue in the first place. Seems related to `fraction.js@4.3.x` in combination with Webpack.

**Comment by infusion** [comment] 2023-08-31 07:33
Could we run the test without fixing the version please? Otherwise we will gain no info on how to solve this issue in the long run.

**Comment by josdejong** [comment] 2023-08-31 07:36
Ok we can wait for a bit more, but I prefer not to wait for too long (possibly exposing more and more people to the problem).

Even when the workaround is published we can still ask someone to test with `mathjs@11.10.0` and `fraction.js@4.3.3`, right?

**Comment by infusion** [comment] 2023-08-31 07:38
Definitely, but as I said, 4.3.3 should be the same as 4.2.0. So hopefully it is fixed anyway for those people. Do you think it's a webpack problem?

BTW Sorry for introducing this issue.

**Comment by Nagrom33** [comment] 2023-08-31 07:39
Thanks @josdejong for the fast responses, gonna try right now to change package.json
    "mathjs": "11.10.1",

- Step 1: Changed Package.json
- Step 2: rm -rf package-lock.json && rm -rf yarn.lock && rm -rf node_modules/
- Step 3: npm install
- Step 4: npm run start
- Step 5: Open page in incognito

Getting error:
```
Uncaught TypeError: fraction_js__WEBPACK_IMPORTED_MODULE_0__.prototype is undefined
    createFractionClass Fraction.js:9
    assertAndCreate factory.js:35
    js pureFunctionsAny.generated.js:62
    factory react refresh:6
    Webpack 31
```

What do i miss?

**Comment by josdejong** [comment] 2023-08-31 07:41
@Nagrom33 thanks for testing, please let us know if `fraction.js@4.3.3` solves the issue. I've not yet published `mathjs@11.10.1` (locking `fraction.js@4.2.0`), latest version still is `mathjs@11.10.0`.

**Comment by Nagrom33** [comment] 2023-08-31 08:00
Tried package.json:

-    "mathjs": "^11.10.0",
-    "fraction.js": "^4.3.3"

Checked my node_modules folder "/node_modules/fraction.js/package.json" it said
```
{
  "name": "fraction.js",
  "title": "fraction.js",
  "version": "4.3.3",
```

But getting the same error:
```
TypeError: "/react/static/media/fraction.5d669f929ffae73460c8.cjs" is not a non-null object
    createFractionClass Fraction.js:9
    assertAndCreate factory.js:35
    js pureFunctionsAny.generated.js:22
    factory react refresh:6
    Webpack 31
lockdown-install.js:1:103865
```

**Comment by infusion** [comment] 2023-08-31 08:01
So webpack has a problem with the .cjs filename then?

**Comment by josdejong** [comment] 2023-08-31 08:04
@Nagrom33 thanks that is useful info. What version of Webpack are you using? Would it be possible for you to put together an empty webpack project with mathjs and fraction.js that reproduces the issue so we can do debugging on it?

**Comment by infusion** [comment] 2023-08-31 08:07
I renamed the cjs file to an ordinary js file again in 4.3.4

**Comment by josdejong** [comment] 2023-08-31 08:07
> So webpack has a problem with the .cjs filename then?

Yeah maybe that's it. Maybe related to this open issue: https://github.com/facebook/create-react-app/issues/12700

**Comment by Nagrom33** [comment] 2023-08-31 08:11
> @Nagrom33 thanks that is useful info. What version of Webpack are you using? Would it be possible for you to put together an empty webpack project with mathjs and fraction.js that reproduces the issue so we can do debugging on it?

I used react create app: "react-scripts": "^5.0.1"

**Comment by josdejong** [comment] 2023-08-31 08:27
@infusion I managed to reproduce the issue in a plain `create-react-app`, see: https://github.com/josdejong/test-mathjs-issue-3022

The issue is indeed fixed with `fraction.js@4.3.4`.

**Comment by Nagrom33** [comment] 2023-08-31 08:40
> @infusion I managed to reproduce the issue in a plain `create-react-app` project, see: https://github.com/josdejong/test-mathjs-issue-3022
> 
> The issue is indeed fixed with `fraction.js@4.3.4`.

Thanks @josdejong !

This works for me! 
- Step 1: rm -rf package-lock.json && rm -rf yarn.lock && rm -rf node_modules/
- Step 2: npm cache clean --force
- Step 3: npm install fraction.js@4.3.4
- Step 4: npm install
- Step 5: npm run start

Maybe to many steps and not all needed but, the problem is solved!!

**Comment by josdejong** [comment] 2023-08-31 08:51
I've now published `mathjs@11.10.1` with `fraction.js@^4.3.4`.

**Comment by infusion** [comment] 2023-08-31 09:01
The problem with the renaming I see is this: As soon as you give the package a `type: "module"` in the package.json, it is a ESM package, requiring .js files to act like a module. To give backwards compatibility, you can give files the .cjs extension. Since the fraction.js file already exports both, ESM and CommonJS, I tried around to not duplicate the file. The way it worked was giving both ESM and CommonJS the .cjs file, which works great. However, webpack seems to have a problem with that. Maybe we have to ship a 100% copy of fraction.js as fraction.cjs.

**Comment by josdejong** [comment] 2023-08-31 09:04
Ah ok. That sort of makes sense. But I guess the ESM and CommonJS versions cannot be the same, since ESM needs to use `export` and `CommonJS` needs to use `module.exports`?

> BTW Sorry for introducing this issue.

I don't blame you at all. The JavaScript ecosystem is just _extremely_ complex for library developers. Having to deal with various ways that you can configure package.json, dealing with CommonJS, ESM, TypeScript, different browsers, different versions of node.js, a lot of different bundlers like Vite, Rollup, Webpack, various CDN's, and things like the deprecated and outdated but widely used `create-react-app` many people being stuck on old versions of Webpack, etc 🤯

**Comment by infusion** [comment] 2023-08-31 09:07
You don't need to use `export` explicitly. I learned from babel back then that you only need to define some attributes, which I do at the end of the file. This way fraction.js was already working as an ESM module for ages, but it is not really an ESM module since the new `type: "module"` attribute was missing.

**Comment by infusion** [comment] 2023-08-31 09:14
Basically, what you have to do to supoort both, is exporting like this:

```
    Object.defineProperty(exports, "__esModule", { 'value': true });
    exports['default'] = Fraction; // Default ESM
    module['exports'] = Fraction; // CommonJS
 ```

**Comment by josdejong** [comment] 2023-08-31 10:21
I have indeed seen that construct before. It feels a bit hacky but if it works it works :). Thanks for sharing.

@infusion shall I close this issue? I think the cause is clear and the issue is fixed in the latest version of fraction.js.

**Comment by infusion** [comment] 2023-08-31 10:25
I was tinkering with your test repo. The problem is indeed this hacky solution. It seems webpack scans for an `export` and does not like a module definition without it. I have the problematic 4.3.1 now running locally within your test setup.

Yes I think we can close this issue.

**Closed by infusion** 2023-08-31 10:25 UTC
Labels: bug
