### ISSUE TITLE
Memory leak when using mathjs in jest tests

### ISSUE THREAD

**Issue by sublayerio** [josdejong/mathjs#1592] opened 2019-08-14 07:42 UTC
I noticed unexpected behaviour when using mathjs in Jest.

I created 16 test files that just import mathjs.

<img width="372" alt="Screenshot 2019-08-14 at 14 39 34" src="https://user-images.githubusercontent.com/44947294/63003006-74cb3f80-bea1-11e9-9020-a48285f09442.png">

When running the tests the memory heap piles up.

<img width="1485" alt="Screenshot 2019-08-14 at 14 38 46" src="https://user-images.githubusercontent.com/44947294/63003117-b5c35400-bea1-11e9-9721-bf08c2ff52fc.png">

**Comment by josdejong** [comment] 2019-08-15 09:28
Thanks for reporting Olivier. 

At first sight I have no clue what could cause this. Since `const mathjs = require('mathjs')` is "passive", I doubt whether mathjs itself can instantiate "something" multiple times, nothing is invoked. Is it really mathjs related, or does it occur too with other libraries? As far as I know, inside a single nodejs process, a `require` is only loaded once. Can it be that Jest does open multiple processes in parallel or so?

**Comment by harrysarson** [comment] 2019-08-15 12:16
Can this be reproduced without using Jest?

**Comment by harrysarson** [comment] 2019-08-15 12:17
Could Jest run each js file in a separate process (or something)? If so then it would make sense for memory usage to increase.

**Comment by keyflight** [comment] 2019-08-15 12:55
I think it has to do with running things in parallel and things not getting cleaned up after tests have run. I opened an issue at jest repo as well to figure that out.

https://github.com/facebook/jest/issues/8832

**Comment by josdejong** [comment] 2019-08-15 13:35
Yeah something like that makes sense. It could be that there is no actual problem though and that the garbage collector simply didn't trigger yet.

**Comment by gwhitney** [comment] 2023-10-06 02:10
Is there still an issue here four years later, or can this be closed?

**Comment by josdejong** [comment] 2023-10-18 11:31
Let's assume it is resolved and close this issue. Please reopen if needed.

**Closed by josdejong** 2023-10-18 11:31 UTC
