### ISSUE TITLE
How to simplify exponent or square root of variable?

### ISSUE THREAD

**Issue by meramos** [josdejong/mathjs#2502] opened 2022-03-27 03:31 UTC
I'm using `math.simplify()` to simplify algebraic equations (for example, simplify `x - 3 + 3 = 4 + 3` so it turns to `x = 7`).

I want to simplify sqrt(x^2) and sqrt(x)^2, but it isn't simplifying any further with the `math.simplify()` function (it stays the same).

I expect `math.simplify(sqrt(x^2))` and `math.simplify(sqrt(x)^2)` to equal `x`, but both stay the same after simplifying it. 

I'm not sure if I'm doing something wrong or if this library doesn't support what I want to do.

**Comment by gwhitney** [comment] 2022-03-27 05:38
@meramos thanks so much for the inquiry and interest in mathjs. Enhancing the `simplify()` function is an active area of development in mathjs right now. Neither of the identities you refer to are as of yet implemented in simplify() at the moment, but we hope that in the fairly near future something along these lines will be. However, care must be taken: for general real x, sqrt(x^2) = abs(x); only for positive x can we be sure that sqrt(x^2) = x. And conversely, working just within the reals, simplifying sqrt(x)^2 to x could enlarge the domain of definition of an expression from say the positive numbers to all real numbers. On the complex numbers, the latter is safe, but knowing how to simplify sqrt(x^2) will depend on what branch cut is taken in the definiton of sqrt, so there may not be any canonical simplification. These details mean that it's hard to know when these simplifications will be available. Note in the meantime that if you use $x^(1/2)$ in place of $sqrt(x)$, I think there are some simplifications that will apply. Of course, all of the same complications occur, but the code for handling simplifications for exponents has been around for a while, from before there was the same concern about whether and how simplifications are changing the values and/or domain of the expression.

All that said, if you could put your request for these simplifications into a comment in issue #927, which is the general compendium of the type of simplification you propose, that would be very helpful as then we can close this issue as a partial duplicate of that one. Thanks!

**Comment by meramos** [comment] 2022-03-29 04:46
Thank you very much for your response! Replacing `sqrt` with `^(1/2)` worked for my usecase :+1:

**Comment by gwhitney** [comment] 2022-03-29 06:20
Closing since the particular concern has now been recorded in the prior general issue (thanks!)

**Closed by gwhitney** 2022-03-29 06:20 UTC
Labels: question
